### ISSUE TITLE
Crash after closing "correct message" box

### ISSUE THREAD

**Issue by clavinet** [dino/dino#1058]
Operating System: openSUSE Tumbleweed 20210514
KDE Plasma Version: 5.21.5
KDE Frameworks Version: 5.82.0
Qt Version: 5.15.2
Kernel Version: 5.12.3-1-default
OS Type: 64-bit
Graphics Platform: X11

I'm using this package
https://build.opensuse.org/package/show/network:messaging:xmpp:dino/dino
which is based on the latest commit
https://github.com/dino/dino/commit/686035ca1ee65d8180585d0e8c4b30faa0caacc4

How to reproduce crash:
- open two chats
- post something in first chat
- open "correct last message" box with Shift + Arrow Up
- close box
- switch to second chat
- crash

This message appears in stdout:

> (dino:23449): Gtk-WARNING **: 21:35:04.001: Can't set a target list on a widget until you've called gtk_drag_dest_set() to make the widget into a drag destination
Segmentation fault (core dumped)

**Comment by fiaxh** [comment]
I can't reproduce this, so I'll need a stack trace from you.

Please install debug symbols ([`dino-debuginfo`](https://build.opensuse.org/package/binary/download/network:messaging:xmpp:dino/dino/openSUSE_Tumbleweed/i586/dino-debuginfo-0.2.0~git112.20210515.686035ca-616.1.i586.rpm)) and obtain a stack trace by doing:

```
gdb dino
> r // Starts dino 
[Do whatever makes Dino crash]
> bt // To obtain the stack trace
```

**Comment by clavinet** [comment]
```
(dino:31093): Gtk-WARNING **: 23:00:33.001: Can't set a target list on a widget until you've called gtk_drag_dest_set() to make the widget into a drag destination

Thread 1 "dino" received signal SIGSEGV, Segmentation fault.
0x00007ffff785ee00 in _gspell_inline_checker_text_buffer_detach_view (spell=0x555557dc02d0 [GspellInlineCheckerTextBuffer], view=0x555555b6b2a0)
    at gspell-inline-checker-text-buffer.c:1451
1451            g_return_if_fail (GTK_IS_TEXT_VIEW (view));
Missing separate debuginfos, use: zypper install gstreamer-plugins-bad-debuginfo-1.18.4-6.3.x86_64 libgstbasecamerabinsrc-1_0-0-debuginfo-1.18.4-6.3.x86_64
(gdb) bt
#0  0x00007ffff785ee00 in _gspell_inline_checker_text_buffer_detach_view (spell=0x555557dc02d0 [GspellInlineCheckerTextBuffer], view=0x555555b6b2a0)
    at gspell-inline-checker-text-buffer.c:1451
#1  0x00007ffff7867a89 in gspell_text_view_dispose (object=0x5555570f65a0 [GspellTextView]) at gspell-text-view.c:332
#2  0x00007ffff6bd3a38 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3486
#3  g_object_unref (_object=0x5555570f65a0) at ../gobject/gobject.c:3416
#4  0x00005555555b439f in dino_ui_spell_checker_finalize (obj=0x5555560446e0 [DinoUiSpellChecker])
    at /usr/src/debug/dino-0.2.0~git112.20210515.686035ca-616.1.x86_64/main/src/ui/chat_input/spell_checker.vala:12
#5  0x00005555555b11fa in dino_ui_spell_checker_unref (instance=0x5555560446e0)
    at /usr/src/debug/dino-0.2.0~git112.20210515.686035ca-616.1.x86_64/main/src/ui/chat_input/spell_checker.vala:9
#6  dino_ui_spell_checker_unref (instance=0x5555560446e0) at spell_checker.c:994
#7  dino_ui_chat_text_view_finalize (obj=0x555555821860 [DinoUiChatTextView])
    at /usr/src/debug/dino-0.2.0~git112.20210515.686035ca-616.1.x86_64/main/src/ui/chat_input/chat_text_view.vala:42
#8  0x00007ffff6bd3ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#9  g_object_unref (_object=0x555555821860) at ../gobject/gobject.c:3416
#10 0x00005555555b0ead in dino_ui_chat_text_view_controller_finalize (obj=0x555556060f10 [DinoUiChatTextViewController])
    at /usr/src/debug/dino-0.2.0~git112.20210515.686035ca-616.1.x86_64/main/src/ui/chat_input/chat_text_view.vala:16
#11 0x00007ffff6bd3ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#12 g_object_unref (_object=0x555556060f10) at ../gobject/gobject.c:3416
#13 0x00005555555d3205 in dino_ui_conversation_summary_message_item_widget_finalize (obj=0x5555558c2f70 [DinoUiConversationSummaryMessageItemWidget])
    at /usr/src/debug/dino-0.2.0~git112.20210515.686035ca-616.1.x86_64/main/src/ui/conversation_content_view/message_widget.vala:86
#14 0x00007ffff6bd3ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#15 g_object_unref (_object=0x5555558c2f70) at ../gobject/gobject.c:3416
#16 0x00007ffff6ad4c43 in g_source_callback_unref (cb_data=0x5555570d3900) at ../glib/gmain.c:1660
#17 g_source_callback_unref (cb_data=0x5555570d3900) at ../glib/gmain.c:1653
#18 0x00007ffff6ad66ac in g_source_destroy_internal (source=0x5555558cf930, context=0x55555571ab50, have_lock=1) at ../glib/gmain.c:1329
#19 0x00007ffff6ad8960 in g_main_dispatch (context=0x55555571ab50) at ../glib/gmain.c:3367
#20 g_main_context_dispatch (context=0x55555571ab50) at ../glib/gmain.c:4055
#21 0x00007ffff6ad8c38 in g_main_context_iterate (context=context@entry=0x55555571ab50, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/gmain.c:4131
#22 0x00007ffff6ad8cef in g_main_context_iteration (context=context@entry=0x55555571ab50, may_block=may_block@entry=1) at ../glib/gmain.c:4196
#23 0x00007ffff6cfa4d5 in g_application_run (application=application@entry=0x5555559ab130 [DinoUiApplication], argc=-9804, argv=<optimized out>) at ../gio/gapplication.c:2560
#24 0x000055555558665f in dino_main (args=<optimized out>, args_length1=<optimized out>)
    at /usr/src/debug/dino-0.2.0~git112.20210515.686035ca-616.1.x86_64/main/src/main.vala:22
#25 0x0000555555582d62 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/dino-0.2.0~git112.20210515.686035ca-616.1.x86_64/main/src/main.vala:9

```

I don't know what's up with this message, because I did install those debuginfo packages:
`Missing separate debuginfos, use: zypper install gstreamer-plugins-bad-debuginfo-1.18.4-6.3.x86_64 libgstbasecamerabinsrc-1_0-0-debuginfo-1.18.4-6.3.x86_64`

**Comment by ericschdt** [comment]
I have the same issue on the same platform
```
#0  0x00007fba4810fe00 in _gspell_inline_checker_text_buffer_detach_view (spell=0x8f02ce0 [GspellInlineCheckerTextBuffer], view=0x21806e0) at gspell-inline-checker-text-buffer.c:1451
#1  0x00007fba48118a89 in gspell_text_view_dispose (object=0x6b939a0 [GspellTextView]) at gspell-text-view.c:332
#2  0x00007fba47369a38 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3486
#3  g_object_unref (_object=0x6b939a0) at ../gobject/gobject.c:3416
#4  0x000000000048a297 in dino_ui_spell_checker_finalize (obj=0x6b971e0 [DinoUiSpellChecker]) at /path/dino/main/src/ui/chat_input/spell_checker.vala:12
#5  0x000000000048a3f9 in dino_ui_spell_checker_unref (instance=0x6b971e0) at /path/dino/main/src/ui/chat_input/spell_checker.vala:9
#6  0x00000000004810bd in dino_ui_chat_text_view_finalize (obj=0x6993130 [DinoUiChatTextView]) at /path/dino/main/src/ui/chat_input/chat_text_view.vala:42
#7  0x00007fba47369ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#8  g_object_unref (_object=0x6993130) at ../gobject/gobject.c:3416
#9  0x00000000004803e9 in dino_ui_chat_text_view_controller_finalize (obj=0x4f46f10 [DinoUiChatTextViewController]) at /path/dino/main/src/ui/chat_input/chat_text_view.vala:16
#10 0x00007fba47369ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#11 g_object_unref (_object=0x4f46f10) at ../gobject/gobject.c:3416
#12 0x00000000004b832c in dino_ui_conversation_summary_message_item_widget_finalize (obj=0x4f75a30 [DinoUiConversationSummaryMessageItemWidget]) at /path/dino/main/src/ui/conversation_content_view/message_widget.vala:86
#13 0x00007fba47369ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#14 g_object_unref (_object=0x4f75a30) at ../gobject/gobject.c:3416
#15 0x00007fba47268c43 in g_source_callback_unref (cb_data=0x51d5b40) at ../glib/gmain.c:1660
#16 g_source_callback_unref (cb_data=0x51d5b40) at ../glib/gmain.c:1653
#17 0x00007fba4726a6ac in g_source_destroy_internal (source=0x8c6a2f0, context=0x2110440, have_lock=1) at ../glib/gmain.c:1329
#18 0x00007fba4726c960 in g_main_dispatch (context=0x2110440) at ../glib/gmain.c:3367
#19 g_main_context_dispatch (context=0x2110440) at ../glib/gmain.c:4055
#20 0x00007fba4726cc38 in g_main_context_iterate (context=context@entry=0x2110440, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4131
#21 0x00007fba4726ccef in g_main_context_iteration (context=context@entry=0x2110440, may_block=may_block@entry=1) at ../glib/gmain.c:4196
#22 0x00007fba474904d5 in g_application_run (application=0x237e130 [DinoUiApplication], argc=1433490292, argv=<optimized out>) at ../gio/gapplication.c:2560
#23 0x000000000042d079 in dino_main (args=0x7ffe557155e8, args_length1=1) at /path/dino/main/src/main.vala:22
#24 0x000000000042d27e in main (argc=1, argv=0x7ffe557155e8) at /path/dino/main/src/main.vala:9
```

Dino crashes every now and then out of sudden.

**Comment by clavinet** [comment]
It mentions gspell but I have spell checking disabled. Guess it's still loaded anyway.

**Comment by LAGonauta** [comment]
Dino on Windows shows the same issue.
Sorry, no debug information for libraries :/

```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffbddc16b05 in ?? () from C:\Program Files\dino\bin\libgspell-1-2.dll
(gdb) bt
#0  0x00007ffbddc16b05 in ?? ()
   from C:\Program Files\dino\bin\libgspell-1-2.dll
#1  0x00007ffbddc200da in ?? ()
   from C:\Program Files\dino\bin\libgspell-1-2.dll
#2  0x00007ffbf2bfb863 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#3  0x00007ff67584a4d5 in dino_ui_spell_checker_finalize (obj=0x1ac369020e0)
    at main/src/ui/chat_input/spell_checker.c:656
#4  0x00007ff67584a776 in dino_ui_spell_checker_unref (instance=0x1ac369020e0)
    at main/src/ui/chat_input/spell_checker.c:699
#5  dino_ui_spell_checker_unref (instance=0x1ac369020e0)
    at main/src/ui/chat_input/spell_checker.c:694
#6  0x00007ff67584500f in dino_ui_chat_text_view_finalize (obj=0x1ac36481d10)
    at main/src/ui/chat_input/chat_text_view.c:678
#7  0x00007ffbf2bfb8d8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#8  0x00007ff675844c9a in dino_ui_chat_text_view_controller_finalize (
    obj=0x1ac364ef610) at main/src/ui/chat_input/chat_text_view.c:349
#9  0x00007ffbf2bfb8d8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#10 0x00007ff67586557b in dino_ui_conversation_summary_message_item_widget_finalize (obj=0x1ac33b5df70)
    at main/src/ui/conversation_content_view/message_widget.c:1697
#11 0x00007ffbf2bfb8d8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#12 0x00007ff67586435d in dino_ui_conversation_summary_message_meta_item_finalize (obj=0x1ac363356a0)
    at main/src/ui/conversation_content_view/message_widget.c:752
#13 0x00007ffbf2bfb8d8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#14 0x000000006c1cf85a in libgee-0.8-2!gee_abstract_sorted_set_get_type ()
   from C:\Program Files\dino\bin\libgee-0.8-2.dll
#15 0x000000006c1d2471 in libgee-0.8-2!gee_array_list_new_with_closure ()
   from C:\Program Files\dino\bin\libgee-0.8-2.dll
#16 0x00007ffbf2bfb8d8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#17 0x00007ff67585a0fd in dino_ui_conversation_summary_item_meta_data_header_finalize (obj=0x1ac339afd20)
    at main/src/ui/conversation_content_view/conversation_item_skeleton.c:1768
#18 0x00007ffbf2bfb8d8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#19 0x00007ff67585924f in dino_ui_conversation_summary_conversation_item_skeleton_finalize (obj=0x1ac339afb50)
    at main/src/ui/conversation_content_view/conversation_item_skeleton.c:723
#20 0x00007ffbf2bfb8d8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#21 0x00007ffbc130618b in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#22 0x00007ffbc12b960f in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#23 0x00007ff67585d30e in dino_ui_conversation_summary_conversation_view_initialize_for_conversation (self=0x1ac2b99e4d0, conversation=0x1ac33569ce0)
    at main/src/ui/conversation_content_view/conversation_view.c:1097
#24 0x00007ff67581cab4 in dino_ui_conversation_view_controller_select_conversation (self=0x1ac2b0ac560, conversation=0x1ac33569ce0,
    default_initialize_conversation=1)
    at main/src/ui/conversation_view_controller.c:1277
#25 0x00007ff67582ed0a in dino_ui_main_window_controller_select_conversation (
    self=0x1ac2b1b1860, conversation=0x1ac33569ce0, do_reset_search=1,
    default_initialize_conversation=1)
    at main/src/ui/main_window_controller.c:1113
#26 0x00007ffbf2bf6ece in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#27 0x00007ffbf2c08ef9 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#28 0x00007ffbf2c0eb84 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#29 0x00007ffbf2c0efe8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#30 0x00007ff675852eb4 in dino_ui_conversation_selector_real_row_activated (
    base=0x1ac2b9984d0, r=<optimized out>)
    at main/src/ui/conversation_selector/conversation_selector.c:450
#31 0x00007ffbf2bf9be8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#32 0x00007ffbf2bf70e3 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#33 0x00007ffbf2c0ee9b in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#34 0x00007ffbf2c0efe8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#35 0x00007ffbc13db14b in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#36 0x00007ffbf2bf70e3 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#37 0x00007ffbf2c0ee9b in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#38 0x00007ffbf2c0efe8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#39 0x00007ffbc1395fbd in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#40 0x00007ffbf2bf99da in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#41 0x00007ffbf2bf70e3 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#42 0x00007ffbf2c0ee9b in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#43 0x00007ffbf2c0efe8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#44 0x00007ffbc1392fb3 in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#45 0x00007ffbc13945cb in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#46 0x00007ffbc13977b4 in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#47 0x00007ffbc135c61d in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#48 0x00007ffbc1531b0c in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#49 0x00007ffbc1282dc1 in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#50 0x00007ffbf2bf70e3 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#51 0x00007ffbf2c0e42b in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#52 0x00007ffbf2c0efe8 in ?? ()
   from C:\Program Files\dino\bin\libgobject-2.0-0.dll
#53 0x00007ffbc1533425 in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#54 0x00007ffbc13e12df in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#55 0x00007ffbc13e3308 in ?? () from C:\Program Files\dino\bin\libgtk-3-0.dll
#56 0x00007ffbc88bf56a in ?? () from C:\Program Files\dino\bin\libgdk-3-0.dll
#57 0x00007ffbc88f66bf in ?? () from C:\Program Files\dino\bin\libgdk-3-0.dll
#58 0x00007ffbc51288f4 in ?? ()
   from C:\Program Files\dino\bin\libglib-2.0-0.dll
#59 0x00007ffbc512ba46 in ?? ()
   from C:\Program Files\dino\bin\libglib-2.0-0.dll
#60 0x00007ffbc512bd61 in ?? ()
   from C:\Program Files\dino\bin\libglib-2.0-0.dll
#61 0x00007ffbc87abacd in ?? ()
   from C:\Program Files\dino\bin\libgio-2.0-0.dll
#62 0x00007ff67581167f in dino_main (args=<optimized out>,
    args@entry=0x1ac2a3edc70, args_length1=<optimized out>,
    args_length1@entry=1) at main/src/main.c:119
#63 0x00007ff675886ca4 in main (argc=1, argv=0x1ac2a3edc70)
    at main/src/main.c:159
```
