### ISSUE TITLE
Dino crashed: SEGV in gspell-inline-checker-text-buffer

### ISSUE THREAD

**Issue by ericschdt** [dino/dino#1059]
Dino git 686035ca1ee65d8180585d0e8c4b30faa0caacc4
OpenSUSE TW

Dino crashed when I clicked on top most MUC chat to see new messages.
Here's the stacktrace gdb gave me:

```
Thread 12 (Thread 0x7f4df8ce6640 (LWP 24754)):
warning: Section `.reg-xstate/24754' in core file too small.
#0  0x00007f4dfacb75cf in __GI___poll (fds=0xbd2bf0, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f4dfadf5bce in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0xbd2bf0, timeout=<optimized out>, context=0xbd3f20) at ../glib/gmain.c:4434
#2  g_main_context_iterate (context=context@entry=0xbd3f20, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4126
#3  0x00007f4dfadf5cef in g_main_context_iteration (context=0xbd3f20, may_block=may_block@entry=1) at ../glib/gmain.c:4196
#4  0x00007f4dfadf5d41 in glib_worker_main (data=<optimized out>) at ../glib/gmain.c:6089
#5  0x00007f4dfae1f72e in g_thread_proxy (data=0xbc8640) at ../glib/gthread.c:826
#6  0x00007f4dfaba3299 in start_thread (arg=0x7f4df8ce6640) at pthread_create.c:481
#7  0x00007f4dfacc24a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 11 (Thread 0x7f4df3fff640 (LWP 24755)):
warning: Section `.reg-xstate/24755' in core file too small.
#0  0x00007f4dfacb75cf in __GI___poll (fds=0x3616e60, nfds=7, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f4dfadf5bce in g_main_context_poll (priority=<optimized out>, n_fds=7, fds=0x3616e60, timeout=<optimized out>, context=0xbe2540) at ../glib/gmain.c:4434
#2  g_main_context_iterate (context=0xbe2540, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4126
#3  0x00007f4dfadf5f2b in g_main_loop_run (loop=0xbe2630) at ../glib/gmain.c:4329
#4  0x00007f4dfb056166 in gdbus_shared_thread_func (user_data=0xbe2510) at ../gio/gdbusprivate.c:280
#5  0x00007f4dfae1f72e in g_thread_proxy (data=0xbda400) at ../glib/gthread.c:826
#6  0x00007f4dfaba3299 in start_thread (arg=0x7f4df3fff640) at pthread_create.c:481
#7  0x00007f4dfacc24a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7f4dce246640 (LWP 24861)):
warning: Section `.reg-xstate/24861' in core file too small.
#0  0x00007f4dfabafa9a in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x21248c8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
#1  0x00007f4dfabafaff in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x21248c8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ../sysdeps/nptl/futex-internal.c:123
#2  0x00007f4dfaba9260 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x2124878, cond=0x21248a0) at pthread_cond_wait.c:504
#3  __pthread_cond_wait (cond=0x21248a0, mutex=0x2124878) at pthread_cond_wait.c:619
#4  0x00007f4df11492bb in cnd_wait (mtx=0x2124878, cond=0x21248a0) at ../include/c11/threads_posix.h:155
#5  util_queue_thread_func (input=<optimized out>) at ../src/util/u_queue.c:294
#6  0x00007f4df1149177 in impl_thrd_routine.lto_priv.1.lto_priv () at ../src/util/ralloc.c:315
#7  0x00007f4dfaba3299 in start_thread (arg=0x7f4dce246640) at pthread_create.c:481
#8  0x00007f4dfacc24a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7f4df1f1e640 (LWP 24859)):
warning: Section `.reg-xstate/24859' in core file too small.
#0  0x00007f4dfacb75cf in __GI___poll (fds=0x7f4dd4001360, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f4dfadf5bce in g_main_context_poll (priority=<optimized out>, n_fds=2, fds=0x7f4dd4001360, timeout=<optimized out>, context=0xfa3f30) at ../glib/gmain.c:4434
#2  g_main_context_iterate (context=0xfa3f30, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4126
#3  0x00007f4dfadf5f2b in g_main_loop_run (loop=loop@entry=0xfa3d60) at ../glib/gmain.c:4329
#4  0x00007f4df2a66093 in provider_thread (data=0xe41d30) at ../sys/v4l2/gstv4l2deviceprovider.c:403
#5  0x00007f4dfae1f72e in g_thread_proxy (data=0xf45640) at ../glib/gthread.c:826
#6  0x00007f4dfaba3299 in start_thread (arg=0x7f4df1f1e640) at pthread_create.c:481
#7  0x00007f4dfacc24a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7f4da24a8640 (LWP 24868)):
warning: Section `.reg-xstate/24868' in core file too small.
#0  0x00007f4dfacb75cf in __GI___poll (fds=fds@entry=0x7f4d9c001ce0, nfds=nfds@entry=3, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f4df2db5162 in poll (__timeout=-1, __nfds=3, __fds=0x7f4d9c001ce0) at /usr/include/bits/poll2.h:47
#2  poll_func (ufds=0x7f4d9c001ce0, nfds=3, timeout=-1, userdata=0xf65270) at pulse/thread-mainloop.c:70
#3  0x00007f4df2d9ebe9 in pa_mainloop_poll (m=m@entry=0x35051c0) at pulse/mainloop.c:842
#4  0x00007f4df2da923f in pa_mainloop_iterate (m=m@entry=0x35051c0, block=block@entry=1, retval=retval@entry=0x0) at pulse/mainloop.c:924
#5  0x00007f4df2da92f0 in pa_mainloop_run (m=0x35051c0, retval=0x0) at pulse/mainloop.c:942
#6  0x00007f4df2db9159 in thread (userdata=0x10c0220) at pulse/thread-mainloop.c:101
#7  0x00007f4df2d552b8 in internal_thread_func (userdata=0xfdddd0) at pulsecore/thread-posix.c:81
#8  0x00007f4dfaba3299 in start_thread (arg=0x7f4da24a8640) at pthread_create.c:481
#9  0x00007f4dfacc24a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7f4dcda45640 (LWP 24862)):
warning: Section `.reg-xstate/24862' in core file too small.
--Type <RET> for more, q to quit, c to continue without paging--c
#0  0x00007f4dfabafa9a in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x21248c8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
#1  0x00007f4dfabafaff in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x21248c8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ../sysdeps/nptl/futex-internal.c:123
#2  0x00007f4dfaba9260 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x2124878, cond=0x21248a0) at pthread_cond_wait.c:504
#3  __pthread_cond_wait (cond=0x21248a0, mutex=0x2124878) at pthread_cond_wait.c:619
#4  0x00007f4df11492bb in cnd_wait (mtx=0x2124878, cond=0x21248a0) at ../include/c11/threads_posix.h:155
#5  util_queue_thread_func (input=<optimized out>) at ../src/util/u_queue.c:294
#6  0x00007f4df1149177 in impl_thrd_routine.lto_priv.1.lto_priv () at ../src/util/ralloc.c:315
#7  0x00007f4dfaba3299 in start_thread (arg=0x7f4dcda45640) at pthread_create.c:481
#8  0x00007f4dfacc24a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7f4db6613640 (LWP 24867)):
warning: Section `.reg-xstate/24867' in core file too small.
#0  0x00007f4dfacb75cf in __GI___poll (fds=0x340d160, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f4dfadf5bce in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x340d160, timeout=<optimized out>, context=0x340d070) at ../glib/gmain.c:4434
#2  g_main_context_iterate (context=context@entry=0x340d070, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4126
#3  0x00007f4dfadf5cef in g_main_context_iteration (context=context@entry=0x340d070, may_block=may_block@entry=1) at ../glib/gmain.c:4196
#4  0x00007f4dcc21387d in dconf_gdbus_worker_thread (user_data=0x340d070) at ../gdbus/dconf-gdbus-thread.c:82
#5  0x00007f4dfae1f72e in g_thread_proxy (data=0x3406c60) at ../glib/gthread.c:826
#6  0x00007f4dfaba3299 in start_thread (arg=0x7f4db6613640) at pthread_create.c:481
#7  0x00007f4dfacc24a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7f4df271f640 (LWP 24858)):
warning: Section `.reg-xstate/24858' in core file too small.
#0  0x00007f4dfacb75cf in __GI___poll (fds=fds@entry=0x7f4de0007170, nfds=nfds@entry=3, timeout=timeout@entry=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f4df2db5162 in poll (__timeout=-1, __nfds=3, __fds=0x7f4de0007170) at /usr/include/bits/poll2.h:47
#2  poll_func (ufds=0x7f4de0007170, nfds=3, timeout=-1, userdata=0x1a60dd0) at pulse/thread-mainloop.c:70
#3  0x00007f4df2d9ebe9 in pa_mainloop_poll (m=m@entry=0xf66c50) at pulse/mainloop.c:842
#4  0x00007f4df2da923f in pa_mainloop_iterate (m=m@entry=0xf66c50, block=block@entry=1, retval=retval@entry=0x0) at pulse/mainloop.c:924
#5  0x00007f4df2da92f0 in pa_mainloop_run (m=0xf66c50, retval=0x0) at pulse/mainloop.c:942
#6  0x00007f4df2db9159 in thread (userdata=0xf66c00) at pulse/thread-mainloop.c:101
#7  0x00007f4df2d552b8 in internal_thread_func (userdata=0xf66dd0) at pulsecore/thread-posix.c:81
#8  0x00007f4dfaba3299 in start_thread (arg=0x7f4df271f640) at pthread_create.c:481
#9  0x00007f4dfacc24a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7f4dcd244640 (LWP 24863)):
warning: Section `.reg-xstate/24863' in core file too small.
#0  0x00007f4dfabafa9a in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x21248c8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
#1  0x00007f4dfabafaff in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x21248c8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ../sysdeps/nptl/futex-internal.c:123
#2  0x00007f4dfaba9260 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x2124878, cond=0x21248a0) at pthread_cond_wait.c:504
#3  __pthread_cond_wait (cond=0x21248a0, mutex=0x2124878) at pthread_cond_wait.c:619
#4  0x00007f4df11492bb in cnd_wait (mtx=0x2124878, cond=0x21248a0) at ../include/c11/threads_posix.h:155
#5  util_queue_thread_func (input=<optimized out>) at ../src/util/u_queue.c:294
#6  0x00007f4df1149177 in impl_thrd_routine.lto_priv.1.lto_priv () at ../src/util/ralloc.c:315
#7  0x00007f4dfaba3299 in start_thread (arg=0x7f4dcd244640) at pthread_create.c:481
#8  0x00007f4dfacc24a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f4d7ffff640 (LWP 24893)):
warning: Section `.reg-xstate/24893' in core file too small.
#0  0x00007f4dfac89be5 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=req@entry=0x7f4d7fffea50, rem=rem@entry=0x7f4d7fffea60) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:43
#1  0x00007f4dfac8ee77 in __GI___nanosleep (req=req@entry=0x7f4d7fffea50, rem=rem@entry=0x7f4d7fffea60) at ../sysdeps/unix/sysv/linux/nanosleep.c:25
#2  0x00007f4dfae211af in g_usleep (microseconds=microseconds@entry=100000) at ../glib/gtimer.c:277
#3  0x00007f4dfc184c5a in ___lambda54_ () at hazardpointer.c:410
#4  ____lambda54__gthread_func (self=<optimized out>) at hazardpointer.c:419
#5  0x00007f4dfae1f72e in g_thread_proxy (data=0x3ad5000) at ../glib/gthread.c:826
#6  0x00007f4dfaba3299 in start_thread (arg=0x7f4d7ffff640) at pthread_create.c:481
#7  0x00007f4dfacc24a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f4df0d14640 (LWP 24860)):
warning: Section `.reg-xstate/24860' in core file too small.
#0  0x00007f4dfabafa9a in __futex_abstimed_wait_common64 (futex_word=futex_word@entry=0x21248c8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at ../sysdeps/nptl/futex-internal.c:74
#1  0x00007f4dfabafaff in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x21248c8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ../sysdeps/nptl/futex-internal.c:123
#2  0x00007f4dfaba9260 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x2124878, cond=0x21248a0) at pthread_cond_wait.c:504
#3  __pthread_cond_wait (cond=0x21248a0, mutex=0x2124878) at pthread_cond_wait.c:619
#4  0x00007f4df11492bb in cnd_wait (mtx=0x2124878, cond=0x21248a0) at ../include/c11/threads_posix.h:155
#5  util_queue_thread_func (input=<optimized out>) at ../src/util/u_queue.c:294
#6  0x00007f4df1149177 in impl_thrd_routine.lto_priv.1.lto_priv () at ../src/util/ralloc.c:315
#7  0x00007f4dfaba3299 in start_thread (arg=0x7f4df0d14640) at pthread_create.c:481
#8  0x00007f4dfacc24a3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f4df99a4f80 (LWP 24753)):
#0  0x00007f4dfbc98e00 in _gspell_inline_checker_text_buffer_detach_view (spell=0x1d47a30 [GspellInlineCheckerTextBuffer], view=0x3d57de0) at gspell-inline-checker-text-buffer.c:1451
#1  0x00007f4dfbca1a89 in gspell_text_view_dispose (object=0x3603260 [GspellTextView]) at gspell-text-view.c:332
#2  0x00007f4dfaef2a38 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3486
#3  g_object_unref (_object=0x3603260) at ../gobject/gobject.c:3416
#4  0x000000000048a297 in dino_ui_spell_checker_finalize (obj=0x69a99a0 [DinoUiSpellChecker]) at /path/dino/main/src/ui/chat_input/spell_checker.vala:12
#5  0x000000000048a3f9 in dino_ui_spell_checker_unref (instance=0x69a99a0) at /path/dino/main/src/ui/chat_input/spell_checker.vala:9
#6  0x00000000004810bd in dino_ui_chat_text_view_finalize (obj=0x4d7a6b0 [DinoUiChatTextView]) at /path/dino/main/src/ui/chat_input/chat_text_view.vala:42
#7  0x00007f4dfaef2ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#8  g_object_unref (_object=0x4d7a6b0) at ../gobject/gobject.c:3416
#9  0x00000000004803e9 in dino_ui_chat_text_view_controller_finalize (obj=0x83731d0 [DinoUiChatTextViewController]) at /path/dino/main/src/ui/chat_input/chat_text_view.vala:16
#10 0x00007f4dfaef2ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#11 g_object_unref (_object=0x83731d0) at ../gobject/gobject.c:3416
#12 0x00000000004b832c in dino_ui_conversation_summary_message_item_widget_finalize (obj=0x3584a30 [DinoUiConversationSummaryMessageItemWidget]) at /path/dino/main/src/ui/conversation_content_view/message_widget.vala:86
#13 0x00007f4dfaef2ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#14 g_object_unref (_object=0x3584a30) at ../gobject/gobject.c:3416
#15 0x00000000004b5b1b in dino_ui_conversation_summary_message_meta_item_finalize (obj=0x5bc14e0 [DinoUiConversationSummaryMessageMetaItem]) at /path/dino/main/src/ui/conversation_content_view/message_widget.vala:14
#16 0x00007f4dfaef2ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#17 g_object_unref (_object=0x5bc14e0) at ../gobject/gobject.c:3416
#18 0x00007f4dfc15e3fb in _vala_array_destroy (destroy_func=0x42bdf0 <g_object_unref@plt>, array_length=<optimized out>, array=0x53a7450) at arraylist.c:2987
#19 _vala_array_free (destroy_func=0x42bdf0 <g_object_unref@plt>, array_length=<optimized out>, array=0x53a7450) at arraylist.c:2998
#20 gee_array_list_finalize (obj=0x53c54c0 [GeeArrayList]) at arraylist.c:2886
#21 0x00007f4dfaef2ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#22 g_object_unref (_object=0x53c54c0) at ../gobject/gobject.c:3416
#23 0x00000000004a51ee in dino_ui_conversation_summary_item_meta_data_header_finalize (obj=0x3993a20 [DinoUiConversationSummaryItemMetaDataHeader]) at /path/dino/main/src/ui/conversation_content_view/conversation_item_skeleton.vala:115
#24 0x00007f4dfaef2ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#25 g_object_unref (_object=0x3993a20) at ../gobject/gobject.c:3416
#26 0x00000000004a25dc in dino_ui_conversation_summary_conversation_item_skeleton_finalize (obj=0x3a085b0 [DinoUiConversationSummaryConversationItemSkeleton]) at /path/dino/main/src/ui/conversation_content_view/conversation_item_skeleton.vala:24
#27 0x00007f4dfaef2ac4 in g_object_unref (_object=<optimized out>) at ../gobject/gobject.c:3524
#28 g_object_unref (_object=0x3a085b0) at ../gobject/gobject.c:3416
#29 0x00007f4dfb65d26e in gtk_container_remove (container=0xf13150 [DinoUiSizeRequestBox], widget=0x3a085b0 [DinoUiConversationSummaryConversationItemSkeleton]) at gtkcontainer.c:1910
#30 0x00000000004ab148 in __lambda83_ (self=0x100e2c0 [DinoUiConversationSummaryConversationView], widget=0x3a085b0 [DinoUiConversationSummaryConversationItemSkeleton]) at /path/dino/main/src/ui/conversation_content_view/conversation_view.vala:486
#31 0x00000000004ab16d in ___lambda83__gtk_callback (widget=0x3a085b0 [DinoUiConversationSummaryConversationItemSkeleton], self=0x100e2c0) at /path/dino/main/src/ui/conversation_content_view/conversation_view.vala:486
#32 0x00007f4dfb613a50 in gtk_box_forall (container=<optimized out>, include_internals=<optimized out>, callback=0x4ab14a <___lambda83__gtk_callback>, callback_data=0x100e2c0) at gtkbox.c:2675
#33 0x00000000004ab2f5 in dino_ui_conversation_summary_conversation_view_clear (self=0x100e2c0 [DinoUiConversationSummaryConversationView]) at /path/dino/main/src/ui/conversation_content_view/conversation_view.vala:486
#34 0x00000000004a7364 in dino_ui_conversation_summary_conversation_view_initialize_for_conversation (self=0x100e2c0 [DinoUiConversationSummaryConversationView], conversation=0x3a09280 [DinoEntitiesConversation]) at /path/dino/main/src/ui/conversation_content_view/conversation_view.vala:206
#35 0x000000000043dcab in dino_ui_conversation_view_controller_select_conversation (self=0x33e0090 [DinoUiConversationViewController], conversation=0x3a09280 [DinoEntitiesConversation], default_initialize_conversation=1) at /path/dino/main/src/ui/conversation_view_controller.vala:133
#36 0x000000000045cddd in dino_ui_main_window_controller_select_conversation (self=0x7f4de000eba0 [DinoUiMainWindowController], conversation=0x3a09280 [DinoEntitiesConversation], do_reset_search=1, default_initialize_conversation=1) at /path/dino/main/src/ui/main_window_controller.vala:103
#37 0x000000000045bf0e in __lambda203_ (self=0x7f4de000eba0 [DinoUiMainWindowController], conversation=0x3a09280 [DinoEntitiesConversation]) at /path/dino/main/src/ui/main_window_controller.vala:56
#38 0x000000000045bf37 in ___lambda203__dino_ui_conversation_selector_conversation_selected (_sender=0xfd6230 [DinoUiConversationSelector], conversation=0x3a09280 [DinoEntitiesConversation], self=0x7f4de000eba0) at /path/dino/main/src/ui/main_window_controller.vala:56
#42 0x00007f4dfaf06b3f in <emit signal ??? on instance 0xfd6230 [DinoUiConversationSelector]> (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3553
    #39 0x00007f4dfaeed69f in g_closure_invoke (closure=0xe5bca0, return_value=return_value@entry=0x0, n_param_values=2, param_values=param_values@entry=0x7ffee06984b0, invocation_hint=invocation_hint@entry=0x7ffee0698430) at ../gobject/gclosure.c:810
    #40 0x00007f4dfaefffab in signal_emit_unlocked_R (node=node@entry=0xe55290, detail=detail@entry=0, instance=instance@entry=0xfd6230, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7ffee06984b0) at ../gobject/gsignal.c:3741
    #41 0x00007f4dfaf069d9 in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7ffee0698650) at ../gobject/gsignal.c:3497
#43 0x0000000000498cdc in dino_ui_conversation_selector_real_row_activated (base=0xfd6230 [DinoUiConversationSelector], r=0xb75830 [DinoUiConversationSelectorRow]) at /path/dino/main/src/ui/conversation_selector/conversation_selector.vala:51
#44 0x00007f4dfaef0b9a in g_cclosure_marshal_VOID__OBJECTv (closure=0x10510c0, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0x10510f0) at ../gobject/gmarshal.c:1910
#45 0x00007f4dfaeed8c9 in _g_closure_invoke_va (closure=closure@entry=0x10510c0, return_value=return_value@entry=0x0, instance=instance@entry=0xfd6230, args=args@entry=0x7ffee06989e0, n_params=1, param_types=0x10510f0) at ../gobject/gclosure.c:873
#46 0x00007f4dfaf065c9 in g_signal_emit_valist (instance=0xfd6230, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffee06989e0) at ../gobject/gsignal.c:3406
#47 0x00007f4dfaf06b3f in g_signal_emit (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3553
#48 0x00007f4dfb72ad59 in gtk_list_box_select_and_activate_full (grab_focus=1, row=0xb75830 [DinoUiConversationSelectorRow], box=0xfd6230 [DinoUiConversationSelector]) at gtklistbox.c:1820
#49 gtk_list_box_select_and_activate_full (grab_focus=1, row=0xb75830 [DinoUiConversationSelectorRow], box=0xfd6230 [DinoUiConversationSelector]) at gtklistbox.c:1812
#50 gtk_list_box_multipress_gesture_released (gesture=<optimized out>, n_press=1, x=<optimized out>, y=<optimized out>, box=0xfd6230 [DinoUiConversationSelector]) at gtklistbox.c:2016
#51 0x00007f4dfb8d02c7 in _gtk_marshal_VOID__INT_DOUBLE_DOUBLEv (closure=closure@entry=0xe54bd0, return_value=return_value@entry=0x0, instance=instance@entry=0xe7b690, args=args@entry=0x7ffee0698d20, marshal_data=marshal_data@entry=0x0, n_params=n_params@entry=3, param_types=0xf6d970) at gtkmarshalers.c:4803
#52 0x00007f4dfaeed8c9 in _g_closure_invoke_va (closure=closure@entry=0xe54bd0, return_value=return_value@entry=0x0, instance=instance@entry=0xe7b690, args=args@entry=0x7ffee0698d20, n_params=3, param_types=0xf6d970) at ../gobject/gclosure.c:873
#53 0x00007f4dfaf065c9 in g_signal_emit_valist (instance=0xe7b690, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffee0698d20) at ../gobject/gsignal.c:3406
#54 0x00007f4dfaf06b3f in g_signal_emit (instance=instance@entry=0xe7b690, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3553
#55 0x00007f4dfb6ec774 in gtk_gesture_multi_press_end (gesture=gesture@entry=0xe7b690 [GtkGestureMultiPress], sequence=sequence@entry=0x0) at gtkgesturemultipress.c:287
#56 0x00007f4dfaef08fb in g_cclosure_marshal_VOID__BOXEDv (closure=0xf6e720, return_value=<optimized out>, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0xf6e750) at ../gobject/gmarshal.c:1686
#57 0x00007f4dfaeed8c9 in _g_closure_invoke_va (closure=closure@entry=0xf6e720, return_value=return_value@entry=0x0, instance=instance@entry=0xe7b690, args=args@entry=0x7ffee06990a0, n_params=1, param_types=0xf6e750) at ../gobject/gclosure.c:873
#58 0x00007f4dfaf065c9 in g_signal_emit_valist (instance=0xe7b690, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffee06990a0) at ../gobject/gsignal.c:3406
#59 0x00007f4dfaf06b3f in g_signal_emit (instance=instance@entry=0xe7b690, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3553
#60 0x00007f4dfb6e4267 in _gtk_gesture_set_recognized (sequence=0x0, recognized=0, gesture=0xe7b690 [GtkGestureMultiPress]) at gtkgesture.c:346
#61 _gtk_gesture_check_recognized (gesture=gesture@entry=0xe7b690 [GtkGestureMultiPress], sequence=sequence@entry=0x0) at gtkgesture.c:387
#62 0x00007f4dfb6ebfbb in gtk_gesture_handle_event (event=0x3e7f660, controller=0xe7b690 [GtkGestureMultiPress]) at gtkgesture.c:778
#63 gtk_gesture_handle_event (controller=0xe7b690 [GtkGestureMultiPress], event=0x3e7f660) at gtkgesture.c:713
#64 0x00007f4dfb6ecbaf in gtk_gesture_single_handle_event (controller=0xe7b690 [GtkGestureMultiPress], event=0x3e7f660) at gtkgesturesingle.c:222
#65 0x00007f4dfb6b444c in gtk_event_controller_handle_event (controller=0xe7b690 [GtkGestureMultiPress], event=0x3e7f660) at gtkeventcontroller.c:230
#66 0x00007f4dfb8808dd in _gtk_widget_run_controllers (widget=0xfd6230 [DinoUiConversationSelector], event=0x3e7f660, phase=GTK_PHASE_BUBBLE) at gtkwidget.c:7443
#67 0x00007f4dfb8c66a4 in _gtk_marshal_BOOLEAN__BOXEDv (closure=0xe5f1a0, return_value=0x7ffee0699420, instance=<optimized out>, args=<optimized out>, marshal_data=<optimized out>, n_params=<optimized out>, param_types=0xe0ad70) at gtkmarshalers.c:129
#68 0x00007f4dfaeed8c9 in _g_closure_invoke_va (closure=closure@entry=0xe5f1a0, return_value=return_value@entry=0x7ffee0699420, instance=instance@entry=0xfd6230, args=args@entry=0x7ffee06994f0, n_params=1, param_types=0xe0ad70) at ../gobject/gclosure.c:873
#69 0x00007f4dfaf05d32 in g_signal_emit_valist (instance=0xfd6230, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7ffee06994f0) at ../gobject/gsignal.c:3406
#70 0x00007f4dfaf06b3f in g_signal_emit (instance=instance@entry=0xfd6230, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3553
#71 0x00007f4dfb88ec14 in gtk_widget_event_internal.part.0.lto_priv.0 (widget=0xfd6230 [DinoUiConversationSelector], event=0x3e7f660) at gtkwidget.c:7808
#72 0x00007f4dfb735c90 in propagate_event_up (topmost=<optimized out>, event=<optimized out>, widget=0xfd6230 [DinoUiConversationSelector]) at gtkmain.c:2588
#73 propagate_event (widget=widget@entry=0xfd6230 [DinoUiConversationSelector], event=event@entry=0x3e7f660, captured=captured@entry=0, topmost=topmost@entry=0x0) at gtkmain.c:2691
#74 0x00007f4dfb735dbf in gtk_propagate_event (widget=widget@entry=0xfd6230 [DinoUiConversationSelector], event=event@entry=0x3e7f660) at gtkmain.c:2725
#75 0x00007f4dfb736f4b in gtk_main_do_event (event=0x3e7f660) at gtkmain.c:1921
#76 gtk_main_do_event (event=<optimized out>) at gtkmain.c:1691
#77 0x00007f4dfb41e143 in _gdk_event_emit (event=0x3e7f660) at gdkevents.c:73
#78 _gdk_event_emit (event=0x3e7f660) at gdkevents.c:67
#79 0x00007f4dfb454a32 in gdk_event_source_dispatch (source=source@entry=0xba1230, callback=<optimized out>, user_data=<optimized out>) at x11/gdkeventsource.c:367
#80 0x00007f4dfadf58b7 in g_main_dispatch (context=0xba0660) at ../glib/gmain.c:3337
#81 g_main_context_dispatch (context=0xba0660) at ../glib/gmain.c:4055
#82 0x00007f4dfadf5c38 in g_main_context_iterate (context=context@entry=0xba0660, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4131
#83 0x00007f4dfadf5cef in g_main_context_iteration (context=context@entry=0xba0660, may_block=may_block@entry=1) at ../glib/gmain.c:4196
#84 0x00007f4dfb0194d5 in g_application_run (application=0xe0d130 [DinoUiApplication], argc=-529950620, argv=<optimized out>) at ../gio/gapplication.c:2560
#85 0x000000000042d079 in dino_main (args=0x7ffee0699ad8, args_length1=1) at /path/dino/main/src/main.vala:22
#86 0x000000000042d27e in main (argc=1, argv=0x7ffee0699ad8) at /path/dino/main/src/main.vala:9
```

**Comment by ericschdt** [comment]
It happened again. The last line in the log before the core was dumped read this time
```
(dino:5948): Gtk-WARNING **: 12:41:58.002:  Can't set a target list on a widget until you've called gtk_drag_dest_set() to make the widget into a drag destination
````
Not sure if related, but if so, I hope it helps in debugging it.

**Comment by ericschdt** [comment]
It's obviously a duplicate of #1058
