### ISSUE TITLE
Crash in nickname tab completion

### ISSUE THREAD

**Issue by Zash** [dino/dino#1071]
Steps to reproduce: Not sure. Was tab-completing, possibly backwards (shift).

```gdb
Core was generated by `dino'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5199fd2206 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
[Current thread is 1 (Thread 0x7f5197d2e000 (LWP 13063))]
(gdb) bt
#0  0x00007f5199fd2206 in  () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000559be3a00d4b in dino_ui_occupants_tab_completor_next_completion (backwards=0, self=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
) at ./main/src/ui/chat_input/occupants_tab_completer.vala:85
#2  0x0000559be3a00d4b in dino_ui_occupants_tab_completor_on_text_input_key_press (event=<optimized out>, self=<optimized out>) at ./main/src/ui/chat_input/occupants_tab_completer.vala:55
#3  0x0000559be3a00d4b in dino_ui_occupants_tab_completor_on_text_input_key_press (self=<optimized out>, event=<optimized out>) at occupants_tab_completer.c:317
#4  0x00007f519aadc17b in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007f519a23ac8d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007f519a24e365 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007f519a2569ab in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007f519a25797f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007f519aa8a324 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#10 0x00007f519aaaa91b in gtk_window_propagate_key_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007f519aaae42b in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007f519aadc274 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007f519a23aec6 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007f519a256d74 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007f519a25797f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007f519aa8a324 in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#17 0x00007f519a94aa3f in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007f519a94ca83 in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007f519a64e465 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#20 0x00007f519a67f112 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#21 0x00007f519a158f2e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007f519a1591c8 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007f519a15925c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007f519a34ba2d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#25 0x0000559be39cde9f in dino_main (args=<optimized out>, args_length1=<optimized out>) at ./main/src/main.vala:22
#26 0x0000559be39cdc40 in main (argc=<optimized out>, argv=<optimized out>) at ./main/src/main.vala:9
```

**Comment by Zash** [comment]
I still have the core file in case there's anything to be learned from it, but it's over 800M so I'll probably not keep it forever.
