### ISSUE TITLE
Crashing on malformed message

### ISSUE THREAD

**Issue by SkewedZeppelin** [dino/dino#1243]
Version is dino-0.3.0-2.fc36.src.rpm on Fedora 36
A malformed message was posted in a MUC and I was no longer able to click on that MUC without crashing.
After a few tries, the client seems to have gotten stuck on that MUC on open and now always crashes.

Here is a stacktrace:
```
#24901 0x00005555555eb3d3 in dino_ui_util_parse_add_markup_theme (s_=s_@entry=0x555556604e40 "NİCE HEART: \n>", highlight_word=highlight_word@entry=0x5555562d1480 "Beck", parse_links=parse_links@entry=1, parse_text_markup=parse_text_markup@entry=1, parse_quotes=parse_quotes@entry=1, dark_theme=dark_theme@entry=1, theme_dependent=<optimized out>, already_escaped_=<optimized out>) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/util/helper.vala:261
#24902 0x00005555555eb3d3 in dino_ui_util_parse_add_markup_theme (s_=s_@entry=0x555556604ce0 "NİCE HEART: \n>", highlight_word=highlight_word@entry=0x5555562d1480 "Beck", parse_links=parse_links@entry=1, parse_text_markup=parse_text_markup@entry=1, parse_quotes=parse_quotes@entry=1, dark_theme=dark_theme@entry=1, theme_dependent=<optimized out>, already_escaped_=<optimized out>) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/util/helper.vala:261
#24903 0x00005555555eb3d3 in dino_ui_util_parse_add_markup_theme (s_=s_@entry=0x555556604b80 "NİCE HEART: \n>", highlight_word=highlight_word@entry=0x5555562d1480 "Beck", parse_links=parse_links@entry=1, parse_text_markup=parse_text_markup@entry=1, parse_quotes=parse_quotes@entry=1, dark_theme=dark_theme@entry=1, theme_dependent=<optimized out>, already_escaped_=<optimized out>) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/util/helper.vala:261
#24904 0x00005555555eb3d3 in dino_ui_util_parse_add_markup_theme (s_=s_@entry=0x555556604a20 "NİCE HEART: \n>", highlight_word=highlight_word@entry=0x5555562d1480 "Beck", parse_links=parse_links@entry=1, parse_text_markup=parse_text_markup@entry=1, parse_quotes=parse_quotes@entry=1, dark_theme=dark_theme@entry=1, theme_dependent=<optimized out>, already_escaped_=<optimized out>) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/util/helper.vala:261
#24905 0x00005555555eb3d3 in dino_ui_util_parse_add_markup_theme (s_=<optimized out>, highlight_word=0x5555562d1480 "Beck", parse_links=1, parse_text_markup=1, parse_quotes=1, dark_theme=1, theme_dependent=<optimized out>, already_escaped_=<optimized out>) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/util/helper.vala:261
#24906 0x00005555555d9af1 in dino_ui_conversation_summary_message_item_widget_generate_markup_text (item=<optimized out>, self=0x5555565fe9d0) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/conversation_content_view/message_widget.vala:203
#24907 dino_ui_conversation_summary_message_item_widget_update_label (self=0x5555565fe9d0) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/conversation_content_view/message_widget.vala:182
#24908 0x00005555555da727 in dino_ui_conversation_summary_message_item_widget_construct (object_type=<optimized out>, stream_interactor=stream_interactor@entry=0x55555577f350, content_item=content_item@entry=0x5555564fd670) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/conversation_content_view/message_widget.vala:137
#24909 0x00005555555da9b2 in dino_ui_conversation_summary_message_item_widget_new (content_item=0x5555564fd670, stream_interactor=0x55555577f350) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/conversation_content_view/message_widget.vala:105
#24910 dino_ui_conversation_summary_message_meta_item_real_get_widget (base=0x55555652b2e0, type=<optimized out>) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/conversation_content_view/message_widget.vala:24
#24911 0x00005555555d0a2e in dino_ui_conversation_summary_conversation_item_skeleton_construct (object_type=<optimized out>, stream_interactor=stream_interactor@entry=0x55555577f350, conversation=conversation@entry=0x55555629ba70, item=item@entry=0x55555652b2e0, initial_item=1) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/conversation_content_view/conversation_item_skeleton.vala:42
#24912 0x00005555555d0ceb in dino_ui_conversation_summary_conversation_item_skeleton_new (initial_item=<optimized out>, item=0x55555652b2e0, conversation=0x55555629ba70, stream_interactor=0x55555577f350) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/build/conversation_item_skeleton.c:493
#24913 dino_ui_conversation_summary_conversation_view_insert_new (self=self@entry=0x5555556b4710, item=item@entry=0x55555652b2e0) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/conversation_content_view/conversation_view.vala:365
#24914 0x00005555555d1188 in dino_ui_conversation_summary_conversation_view_do_insert_item (self=self@entry=0x5555556b4710, item=item@entry=0x55555652b2e0) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/conversation_content_view/conversation_view.vala:308
#24915 0x00005555555d1dc1 in dino_ui_conversation_summary_conversation_view_display_latest (self=0x5555556b4710) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/conversation_content_view/conversation_view.vala:285
#24916 dino_ui_conversation_summary_conversation_view_initialize_for_conversation (self=0x5555556b4710, conversation=<optimized out>) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/conversation_content_view/conversation_view.vala:208
#24917 0x0000555555596c5c in dino_ui_conversation_view_controller_select_conversation (self=0x55555608fa90, conversation=0x55555629ba70, default_initialize_conversation=<optimized out>) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/conversation_view_controller.vala:138
#24918 0x00005555555a1f40 in dino_ui_main_window_controller_select_conversation (self=0x555555ecceb0, conversation=0x55555629ba70, do_reset_search=1, default_initialize_conversation=1) at /usr/src/debug/dino-0.3.0-2.fc36.x86_64/main/src/ui/main_window_controller.vala:103
```

I tried to remove the offending message using sqlitebrowser, but it won't save edits due to no fts4 module(?).

**Comment by eerielili** [comment]
@SkewedZeppelin Do you still have the issue?

**Comment by SkewedZeppelin** [comment]
I'd have to pull that ancient corrupted database out of my backups. Not even sure if I still have that day since I prune old ones to weekly.

**Comment by balejk** [comment]
I have the same problem in a direct chat with dino 0.5.1 on musl-based Void Linux. My backtrace looks like this (yes, that is a dino XMPP debug log in the body of the problematic message): 
```
#0  0x00007ffff6aa6075 in pcre2_match_8 (code=0x7fffed166180, subject=0x7fffe7472190 <error: Cannot access memory at address 0x7fffe7472190>, length=9787, start_offset=215, options=0, match_data=0x7fffe7560790, mcontext=0x7fffe916e990)
    at src/pcre2_match.c:7283
#1  0x00007ffff7a3f40b in g_match_info_next () from /lib/libglib-2.0.so.0
#2  0x00005555555ead27 in dino_ui_util_parse_add_markup_theme (
    s_=s_@entry=0x7fffecf13ae0 "'>\n    <items node='eu.siacs.conversations.axolotl.bundles:111111111' />\n  </pubsub>\n</iq>\n\nXMPP OUT [juliet@capulet.lit stream:0x55d743ef7ae0 thread:0x55d7416085f0 2026-02-16T08:07:49+0100]\n<r xmlns="..., highlight_word=highlight_word@entry=0x0, parse_links=1, parse_text_markup=parse_text_markup@entry=1, parse_quotes=parse_quotes@entry=0, dark_theme=dark_theme@entry=1, theme_dependent=0x7fffffffcd4c, already_escaped_=0)
    at main/dino.p/src/ui/util/helper.c:1766
#3  0x00005555555eafff in dino_ui_util_parse_add_markup_theme (s_=<optimized out>, highlight_word=<optimized out>, parse_links=<optimized out>, parse_text_markup=1, parse_quotes=<optimized out>, dark_theme=<optimized out>, 
    theme_dependent=0x7fffffffcd4c, already_escaped_=0) at main/dino.p/src/ui/util/helper.c:1743
#4  0x00005555555c5488 in dino_ui_conversation_summary_message_meta_item_generate_markup_text (self=self@entry=0x7fffe755f560, item=<optimized out>, label=0x7fffe8e3def0)
    at main/dino.p/src/ui/conversation_content_view/message_widget.c:1286
#5  0x00005555555c61d1 in dino_ui_conversation_summary_message_meta_item_update_label (self=<optimized out>) at main/dino.p/src/ui/conversation_content_view/message_widget.c:1540
#6  dino_ui_conversation_summary_message_meta_item_construct (object_type=<optimized out>, content_item=<optimized out>, stream_interactor=<optimized out>) at main/dino.p/src/ui/conversation_content_view/message_widget.c:671
#7  0x00005555555b9348 in dino_ui_conversation_summary_content_provider_populate_latest (self=0x7fffed2338a0, conversation=<optimized out>, n=n@entry=40) at main/dino.p/src/ui/conversation_content_view/content_populator.c:349
#8  0x00005555555bc423 in dino_ui_conversation_summary_conversation_view_display_latest (self=0x7fffeeab9a50) at main/dino.p/src/ui/conversation_content_view/conversation_view.c:2066
#9  dino_ui_conversation_summary_conversation_view_initialize_for_conversation (self=0x7fffeeab9a50, conversation=0x7ffff1426b20) at main/dino.p/src/ui/conversation_content_view/conversation_view.c:1419
#10 0x00005555555d88cc in dino_ui_conversation_view_controller_select_conversation (self=0x7fffed2d72a0, conversation=0x7ffff1426b20, default_initialize_conversation=1) at main/dino.p/src/ui/conversation_view_controller.c:1455
#11 0x00005555555e3cc1 in dino_ui_main_window_controller_select_conversation (self=0x7ffff10ae6d0, conversation=0x7ffff1426b20, do_reset_search=1, default_initialize_conversation=1) at main/dino.p/src/ui/main_window_controller.c:1203
#12 0x00007ffff7b356d0 in g_closure_invoke () from /lib/libgobject-2.0.so.0
#13 0x00007ffff7b4a4a3 in ?? () from /lib/libgobject-2.0.so.0
#14 0x00007ffff7b4bec9 in ?? () from /lib/libgobject-2.0.so.0
#15 0x00007ffff7b51f52 in g_signal_emit_valist () from /lib/libgobject-2.0.so.0
#16 0x00007ffff7b51fff in g_signal_emit () from /lib/libgobject-2.0.so.0
#17 0x00005555555cb144 in dino_ui_conversation_selector_row_activated (self=0x7fffeeb01ea0, r=<optimized out>) at main/dino.p/src/ui/conversation_selector/conversation_selector.c:473
#18 0x00007ffff7b38dac in g_cclosure_marshal_VOID__OBJECTv () from /lib/libgobject-2.0.so.0
#19 0x00007ffff7b35929 in ?? () from /lib/libgobject-2.0.so.0
#20 0x00007ffff7b4c018 in ?? () from /lib/libgobject-2.0.so.0
#21 0x00007ffff7b51f52 in g_signal_emit_valist () from /lib/libgobject-2.0.so.0
#22 0x00007ffff7b51fff in g_signal_emit () from /lib/libgobject-2.0.so.0
#23 0x00007ffff6fb6cd7 in ?? () from /lib/libgtk-4.so.1
#24 0x00007ffff6ed57aa in ?? () from /lib/libgtk-4.so.1
#25 0x00007ffff7b35929 in ?? () from /lib/libgobject-2.0.so.0
#26 0x00007ffff7b4c018 in ?? () from /lib/libgobject-2.0.so.0
#27 0x00007ffff7b51f52 in g_signal_emit_valist () from /lib/libgobject-2.0.so.0
#28 0x00007ffff7b51fff in g_signal_emit () from /lib/libgobject-2.0.so.0
#29 0x00007ffff6f82a56 in ?? () from /lib/libgtk-4.so.1
#30 0x00007ffff7b38afd in g_cclosure_marshal_VOID__BOXEDv () from /lib/libgobject-2.0.so.0
#31 0x00007ffff7b35929 in ?? () from /lib/libgobject-2.0.so.0
#32 0x00007ffff7b4c018 in ?? () from /lib/libgobject-2.0.so.0
#33 0x00007ffff7b51f52 in g_signal_emit_valist () from /lib/libgobject-2.0.so.0
#34 0x00007ffff7b51fff in g_signal_emit () from /lib/libgobject-2.0.so.0
#35 0x00007ffff6f7cb9b in ?? () from /lib/libgtk-4.so.1
#36 0x00007ffff6f7d64b in ?? () from /lib/libgtk-4.so.1
#37 0x00007ffff6f8326e in ?? () from /lib/libgtk-4.so.1
#38 0x00007ffff70ae0d6 in ?? () from /lib/libgtk-4.so.1
#39 0x00007ffff6fc2d5e in ?? () from /lib/libgtk-4.so.1
#40 0x00007ffff6fc38d3 in ?? () from /lib/libgtk-4.so.1
#41 0x00007ffff723222e in ?? () from /lib/libgtk-4.so.1
#42 0x00007ffff72cadc9 in ?? () from /lib/libgtk-4.so.1
#43 0x00007ffff7b35929 in ?? () from /lib/libgobject-2.0.so.0
#44 0x00007ffff7b4b293 in ?? () from /lib/libgobject-2.0.so.0
#45 0x00007ffff7b51f52 in g_signal_emit_valist () from /lib/libgobject-2.0.so.0
#46 0x00007ffff7b51fff in g_signal_emit () from /lib/libgobject-2.0.so.0
#47 0x00007ffff7363b77 in ?? () from /lib/libgtk-4.so.1
#48 0x00007ffff72391dc in ?? () from /lib/libgtk-4.so.1
#49 0x00007ffff7a24796 in ?? () from /lib/libglib-2.0.so.0
#50 0x00007ffff7a27d27 in ?? () from /lib/libglib-2.0.so.0
#51 0x00007ffff7a2846c in g_main_context_iteration () from /lib/libglib-2.0.so.0
#52 0x00007ffff6bccdbd in g_application_run () from /lib/libgio-2.0.so.0
#53 0x000055555558ba53 in dino_main (args=0x7fffffffeaa8, args_length1=1) at main/dino.p/src/main.c:138
#54 main (argc=1, argv=0x7fffffffeaa8) at main/dino.p/src/main.c:178
```
