### ISSUE TITLE
GTK4 - crash when answering video call

### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#1267]
Dino b8e84c83268a11ae41ad1d673999362427fd755c amd64 Debian Sid, calling from Conversations 2.10.9+free

```
#0  0x00007fffe1a5e7fe in gst_video_frame_unmap () at /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0
#1  0x00007ffff0063375 in dino_plugins_rtp_sink_texture_from_buffer (self=0x555558474740, buffer=0x7fff500255a0, pixel_aspect_ratio=0x7fffb889beb8) at /gitrepo/dino/plugins/rtp/src/video_widget.vala:133
#2  0x00007ffff0063486 in dino_plugins_rtp_sink_queue_buffer (self=0x555558474740, buf=0x7fff500255a0) at /gitrepo/dino/plugins/rtp/src/video_widget.vala:142
#3  0x00007ffff0063567 in dino_plugins_rtp_sink_real_show_frame (base=0x555558474740, buf=0x7fff500255a0) at /gitrepo/dino/plugins/rtp/src/video_widget.vala:150
#4  0x00007fffe1e748fc in  () at /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#5  0x00007fffe1e764d0 in  () at /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#6  0x00007fffe191ce3d in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#7  0x00007fffe191f0c9 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#8  0x00007fffe1926652 in gst_pad_push () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#9  0x00007fffe19099fb in gst_proxy_pad_chain_default () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#10 0x00007fffe191ce3d in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#11 0x00007fffe191f0c9 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#12 0x00007fffe1926652 in gst_pad_push () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#13 0x00007fffe1e80c4c in  () at /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#14 0x00007fffe191ce3d in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#15 0x00007fffe191f0c9 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#16 0x00007fffe1926652 in gst_pad_push () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#17 0x00007fffe19099fb in gst_proxy_pad_chain_default () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#18 0x00007fffe191ce3d in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#19 0x00007fffe191f0c9 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#20 0x00007fffe1926652 in gst_pad_push () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#21 0x00007fffbb09f55e in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstcoreelements.so
#22 0x00007fffbb09f74d in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstcoreelements.so
#23 0x00007fffe191ce3d in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#24 0x00007fffe191f0c9 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#25 0x00007fffe1926652 in gst_pad_push () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#26 0x00007fffe1e80c4c in  () at /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#27 0x00007fffe191ce3d in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#28 0x00007fffe191f0c9 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#29 0x00007fffe1926652 in gst_pad_push () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#30 0x00007fffe19099fb in gst_proxy_pad_chain_default () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#31 0x00007fffe191ce3d in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#32 0x00007fffe191f0c9 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#33 0x00007fffe1926652 in gst_pad_push () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#34 0x00007fffe1e80c4c in  () at /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0
#35 0x00007fffe191ce3d in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#36 0x00007fffe191f0c9 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#37 0x00007fffe1926652 in gst_pad_push () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#38 0x00007fffe1a1bf21 in  () at /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0
#39 0x00007fffe1a2293b in gst_video_decoder_finish_frame () at /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0
#40 0x00007fffc81efe02 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstvpx.so
#41 0x00007fffe1a24b13 in  () at /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0
#42 0x00007fffe1a24ff3 in  () at /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0
#43 0x00007fffe1a27cb2 in  () at /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0
#44 0x00007fffe191ce3d in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#45 0x00007fffe191f0c9 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#46 0x00007fffe1926652 in gst_pad_push () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#47 0x00007fffe3f6fbf5 in gst_rtp_base_depayload_push () at /usr/lib/x86_64-linux-gnu/libgstrtp-1.0.so.0
#48 0x00007fffe3f70310 in  () at /usr/lib/x86_64-linux-gnu/libgstrtp-1.0.so.0
#49 0x00007fffe191ce3d in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#50 0x00007fffe191f0c9 in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#51 0x00007fffe1926652 in gst_pad_push () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#52 0x00007fffbb09b295 in  () at /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstcoreelements.so
#53 0x00007fffe195629f in  () at /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#54 0x00007ffff6d245da in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#55 0x00007ffff6d23c0d in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#56 0x00007ffff6887b27 in  () at /lib/x86_64-linux-gnu/libc.so.6
#57 0x00007ffff690a78c in  () at /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by danielreuther** [comment]
It appears I'm running into the same issue with a MinGW build. This does not seem to happen when building against GTK3.

```
#0  0x00007fffdd433e2c in libgstvideo-1.0-0!gst_video_frame_unmap () from /c/dino/bin/libgstvideo-1.0-0.dll
#1  0x00007ff83af199b8 in rtp!dino_plugins_rtp_video_stream_new () from /c/dino/lib/dino/plugins/rtp.dll
#2  0x00007ff83af1a4b0 in rtp!dino_plugins_rtp_paintable_queue_set_texture ()
   from /c/dino/lib/dino/plugins/rtp.dll
#3  0x00007ff8270fe87d in libgstbase-1.0-0!gst_base_sink_do_preroll () from /c/dino/bin/libgstbase-1.0-0.dll
#4  0x00007ff8270ff2c1 in libgstbase-1.0-0!gst_base_sink_do_preroll () from /c/dino/bin/libgstbase-1.0-0.dll
#5  0x00007ff827100bf7 in libgstbase-1.0-0!gst_base_sink_do_preroll () from /c/dino/bin/libgstbase-1.0-0.dll
#6  0x00007ff827102bc5 in libgstbase-1.0-0!gst_base_sink_do_preroll () from /c/dino/bin/libgstbase-1.0-0.dll
#7  0x00007fffdd6f7c45 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#8  0x00007fffdd6fa058 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#9  0x00007fffdd7018a3 in libgstreamer-1.0-0!gst_pad_push () from /c/dino/bin/libgstreamer-1.0-0.dll
#10 0x00007fffdd6e4213 in libgstreamer-1.0-0!gst_proxy_pad_chain_default ()
   from /c/dino/bin/libgstreamer-1.0-0.dll
#11 0x00007fffdd6f7c45 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#12 0x00007fffdd6fa058 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#13 0x00007fffdd7018a3 in libgstreamer-1.0-0!gst_pad_push () from /c/dino/bin/libgstreamer-1.0-0.dll
#14 0x00007ff82710d71a in libgstbase-1.0-0!gst_base_src_submit_buffer_list ()
   from /c/dino/bin/libgstbase-1.0-0.dll
#15 0x00007fffdd6f7c45 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#16 0x00007fffdd6fa058 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#17 0x00007fffdd7018a3 in libgstreamer-1.0-0!gst_pad_push () from /c/dino/bin/libgstreamer-1.0-0.dll
#18 0x00007ff82710d71a in libgstbase-1.0-0!gst_base_src_submit_buffer_list ()
   from /c/dino/bin/libgstbase-1.0-0.dll
#19 0x00007fffdd6f7c45 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#20 0x00007fffdd6fa058 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#21 0x00007fffdd7018a3 in libgstreamer-1.0-0!gst_pad_push () from /c/dino/bin/libgstreamer-1.0-0.dll
#22 0x00007fffdd6e4213 in libgstreamer-1.0-0!gst_proxy_pad_chain_default ()
   from /c/dino/bin/libgstreamer-1.0-0.dll
#23 0x00007fffdd6f7c45 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#24 0x00007fffdd6fa058 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#25 0x00007fffdd7018a3 in libgstreamer-1.0-0!gst_pad_push () from /c/dino/bin/libgstreamer-1.0-0.dll
#26 0x00007fffd97e1536 in libgstcoreelements!gst_element_register_streamiddemux ()
   from /c/dino/lib/gstreamer-1.0/libgstcoreelements.dll
#27 0x00007fffd97e16e4 in libgstcoreelements!gst_element_register_streamiddemux ()
   from /c/dino/lib/gstreamer-1.0/libgstcoreelements.dll
#28 0x00007fffdd6f7c45 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#29 0x00007fffdd6fa058 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#30 0x00007fffdd7018a3 in libgstreamer-1.0-0!gst_pad_push () from /c/dino/bin/libgstreamer-1.0-0.dll
#31 0x00007ff82710d71a in libgstbase-1.0-0!gst_base_src_submit_buffer_list ()
--Type <RET> for more, q to quit, c to continue without paging--c
   from /c/dino/bin/libgstbase-1.0-0.dll
#32 0x00007fffdd6f7c45 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#33 0x00007fffdd6fa058 in libgstreamer-1.0-0!gst_flow_get_name () from /c/dino/bin/libgstreamer-1.0-0.dll
#34 0x00007fffdd7018a3 in libgstreamer-1.0-0!gst_pad_push () from /c/dino/bin/libgstreamer-1.0-0.dll
#35 0x00007ff8271085bd in libgstbase-1.0-0!gst_base_src_get_type () from /c/dino/bin/libgstbase-1.0-0.dll
#36 0x00007fffdd73089f in libgstreamer-1.0-0!gst_tag_setter_get_tag_merge_mode () from /c/dino/bin/libgstreamer-1.0-0.dll
#37 0x00007ff848528462 in libglib-2.0-0!g_get_num_processors () from /c/dino/bin/libglib-2.0-0.dll
#38 0x00007ff8485279c1 in libglib-2.0-0!g_test_get_path () from /c/dino/bin/libglib-2.0-0.dll
#39 0x00007ff848556347 in libglib-2.0-0!g_private_replace () from /c/dino/bin/libglib-2.0-0.dll
#40 0x00007ff88cc8af5a in msvcrt!_beginthreadex () from /c/WINDOWS/System32/msvcrt.dll
#41 0x00007ff88cc8b02c in msvcrt!_endthreadex () from /c/WINDOWS/System32/msvcrt.dll
#42 0x00007ff88ce87034 in KERNEL32!BaseThreadInitThunk () from /c/WINDOWS/System32/KERNEL32.DLL
#43 0x00007ff88ec426a1 in ntdll!RtlUserThreadStart () from /c/WINDOWS/SYSTEM32/ntdll.dll
#44 0x0000000000000000 in ?? ()
```

**Comment by foucault** [comment]
Same issue when initiating a call to Conversations; not sure if the other side's client is relevant or not. Slightly more detailed backtrace
Arch Linux;
* dino 0.4.1
* pipewire (and gst plugin) 0.3.76
* gstreamer (and good/bad/ugly/gtk plugins) 1.22.1
* gtk4 4.10.1
* libsrtp 2.5.0

```
Thread 22 "pipewiredevice2" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffbcbfe6c0 (LWP 7472)]
0x00007fffdaf1f457 in gst_video_frame_unmap (frame=0x7fffbcbfc4c0) at ../gstreamer/subprojects/gst-plugins-base/gst-libs/gst/video/video-frame.c:276                                                                                                                                   
276	    for (i = 0; i < frame->info.finfo->n_planes; i++) {
#0  0x00007fffdaf1f457 in gst_video_frame_unmap (frame=0x7fffbcbfc4c0) at ../gstreamer/subprojects/gst-plugins-base/gst-libs/gst/video/video-frame.c:276
#1  0x00007fffdbf8e33d in dino_plugins_rtp_sink_texture_from_buffer.constprop.0 (self=self@entry=0x55555a631940, buffer=buffer@entry=0x7fffac0055d0 [None], pixel_aspect_ratio=pixel_aspect_ratio@entry=0x7fffbcbfcce0) at /usr/src/debug/dino/dino-0.4.1/plugins/rtp/src/video_widget.vala:133
#2  0x00007fffdbf85864 in dino_plugins_rtp_sink_queue_buffer (buf=0x7fffac0055d0 [None], self=0x55555a631940) at /usr/src/debug/dino/dino-0.4.1/plugins/rtp/src/video_widget.vala:142
#3  dino_plugins_rtp_sink_real_show_frame(GstVideoSink*, GstBuffer*) (base=0x55555a631940, buf=0x7fffac0055d0 [None]) at /usr/src/debug/dino/dino-0.4.1/plugins/rtp/src/video_widget.vala:150
#4  0x00007fffdae48793 in gst_base_sink_do_preroll (sink=0x55555a631940, obj=0x7fffac0055d0 [None]) at ../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasesink.c:2514
#5  0x00007fffdae77013 in gst_base_sink_do_sync.constprop.0 (basesink=basesink@entry=0x55555a631940, obj=obj@entry=0x7fffac0055d0 [None], late=late@entry=0x7fffbcbfcf30, step_end=step_end@entry=0x7fffbcbfcf34) at ../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasesink.c:2739
#6  0x00007fffdae7871d in gst_base_sink_chain_unlocked.constprop.0 (basesink=basesink@entry=0x55555a631940, obj=obj@entry=0x7fffac0055d0, is_list=is_list@entry=0, pad=<optimized out>) at ../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasesink.c:3919
#7  0x00007fffdae4ee97 in gst_base_sink_chain_main (basesink=0x55555a631940, pad=<optimized out>, obj=0x7fffac0055d0, is_list=0) at ../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasesink.c:4078
#8  0x00007fffdad5863b in gst_pad_chain_data_unchecked (pad=pad@entry=0x55555a631c90, type=type@entry=4112, data=data@entry=0x7fffac0055d0) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4463
#9  0x00007fffdad5bf0b in gst_pad_push_data (pad=pad@entry=0x55555a6c7620, type=type@entry=4112, data=data@entry=0x7fffac0055d0) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4739
#10 0x00007fffdad5c2c6 in gst_pad_push (pad=0x55555a6c7620, buffer=0x7fffac0055d0 [None]) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4858
#11 0x00007fffdad41d0d in gst_proxy_pad_chain_default (pad=<optimized out>, parent=<optimized out>, buffer=0x7fffac0055d0 [None]) at ../gstreamer/subprojects/gstreamer/gst/gstghostpad.c:127
#12 0x00007fffdad5863b in gst_pad_chain_data_unchecked (pad=pad@entry=0x55555a6ca840, type=type@entry=4112, data=data@entry=0x7fffac0055d0) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4463
#13 0x00007fffdad5bf0b in gst_pad_push_data (pad=pad@entry=0x55555a6c5fe0, type=type@entry=4112, data=data@entry=0x7fffac0055d0) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4739
#14 0x00007fffdad5c2c6 in gst_pad_push (pad=0x55555a6c5fe0, buffer=0x7fffac0055d0 [None]) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4858
#15 0x00007fffdae60252 in gst_base_transform_chain (pad=<optimized out>, parent=0x55555a6c5760, buffer=<optimized out>) at ../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasetransform.c:2391
#16 0x00007fffdad5863b in gst_pad_chain_data_unchecked (pad=pad@entry=0x55555a6c5b70, type=type@entry=4112, data=data@entry=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4463
#17 0x00007fffdad5bf0b in gst_pad_push_data (pad=pad@entry=0x55555a5b88f0, type=type@entry=4112, data=data@entry=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4739
#18 0x00007fffdad5c2c6 in gst_pad_push (pad=0x55555a5b88f0, buffer=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4858
#19 0x00007fffdae60252 in gst_base_transform_chain (pad=<optimized out>, parent=0x55555a5b8120, buffer=<optimized out>) at ../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasetransform.c:2391
#20 0x00007fffdad5863b in gst_pad_chain_data_unchecked (pad=pad@entry=0x55555a5b8530, type=type@entry=4112, data=data@entry=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4463
#21 0x00007fffdad5bf0b in gst_pad_push_data (pad=pad@entry=0x55555a6711d0, type=type@entry=4112, data=data@entry=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4739
#22 0x00007fffdad5c2c6 in gst_pad_push (pad=0x55555a6711d0, buffer=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4858
#23 0x00007fffdad41d0d in gst_proxy_pad_chain_default (pad=<optimized out>, parent=<optimized out>, buffer=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstghostpad.c:127
#24 0x00007fffdad5863b in gst_pad_chain_data_unchecked (pad=pad@entry=0x55555a6cabc0, type=type@entry=4112, data=data@entry=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4463
#25 0x00007fffdad5bf0b in gst_pad_push_data (pad=pad@entry=0x55555a77c620, type=type@entry=4112, data=data@entry=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4739
#26 0x00007fffdad5c2c6 in gst_pad_push (pad=0x55555a77c620, buffer=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4858
#27 0x00007ffff06de96a in gst_tee_handle_data (tee=tee@entry=0x55555a7766e0, data=data@entry=0x7fffac05d590, is_list=is_list@entry=0) at ../gstreamer/subprojects/gstreamer/plugins/elements/gsttee.c:899
#28 0x00007ffff06dea4f in gst_tee_chain (pad=<optimized out>, parent=0x55555a7766e0, buffer=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/plugins/elements/gsttee.c:1026
#29 0x00007fffdad5863b in gst_pad_chain_data_unchecked (pad=pad@entry=0x55555a7769a0, type=type@entry=4112, data=data@entry=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4463
#30 0x00007fffdad5bf0b in gst_pad_push_data (pad=pad@entry=0x55555a7757d0, type=type@entry=4112, data=data@entry=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4739
#31 0x00007fffdad5c2c6 in gst_pad_push (pad=0x55555a7757d0, buffer=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4858
#32 0x00007fffdae60252 in gst_base_transform_chain (pad=<optimized out>, parent=0x55555a7751e0, buffer=<optimized out>) at ../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasetransform.c:2391
#33 0x00007fffdad5863b in gst_pad_chain_data_unchecked (pad=pad@entry=0x55555a7754f0, type=type@entry=4112, data=data@entry=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4463
#34 0x00007fffdad5bf0b in gst_pad_push_data (pad=pad@entry=0x55555a6cd370, type=type@entry=4112, data=data@entry=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4739
#35 0x00007fffdad5c2c6 in gst_pad_push (pad=pad@entry=0x55555a6cd370, buffer=0x7fffac05d590) at ../gstreamer/subprojects/gstreamer/gst/gstpad.c:4858
#36 0x00007fffdae59b9e in gst_base_src_loop (pad=0x55555a6cd370) at ../gstreamer/subprojects/gstreamer/libs/gst/base/gstbasesrc.c:3035
#37 0x00007fffdad8407b in gst_task_func (task=0x55555a77ce70) at ../gstreamer/subprojects/gstreamer/gst/gsttask.c:384
#38 0x00007ffff6a38f63 in g_thread_pool_thread_proxy (data=<optimized out>) at ../glib/glib/gthreadpool.c:350
#39 0x00007ffff6a367c5 in g_thread_proxy (data=0x7fffec018cb0) at ../glib/glib/gthread.c:831
#40 0x00007ffff684cbb5 in start_thread (arg=<optimized out>) at pthread_create.c:444
#41 0x00007ffff68ced90 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
