### ISSUE TITLE
Resource deadlock when switching to non-primary video device before call initiation

### ISSUE THREAD

**Issue by jscott0** [dino/dino#1283]
Hi. First, here's the backtrace. You can see there's a deadlock in `pthread_cond_wait`:
```
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x7fffffffd7a0, op=393, expected=0, futex_word=0x555557711878)
    at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common
    (futex_word=futex_word@entry=0x555557711878, expected=expected@entry=0, clockid=<error reading variable: Cannot access memory at address 0x7fffffffd6e0>, abstime=abstime@entry=0x7fffffffd7a0, private=private@entry=0, cancel=cancel@entry=true) at ./nptl/futex-internal.c:87
#2  0x00007ffff68844bb in __GI___futex_abstimed_wait_cancelable64
    (futex_word=futex_word@entry=0x555557711878, expected=expected@entry=0, clockid=<error reading variable: Cannot access memory at address 0x7fffffffd6e0>, abstime=abstime@entry=0x7fffffffd7a0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007ffff6886f04 in __pthread_cond_wait_common (abstime=0x7fffffffd7a0, clockid=0, mutex=0x555557711828, cond=0x555557711850)
    at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_timedwait64 (cond=cond@entry=0x555557711850, mutex=mutex@entry=0x555557711828, abstime=abstime@entry=0x7fffffffd7a0)
    at ./nptl/pthread_cond_wait.c:643
#5  0x00007fffe3e0ba1b in pw_thread_loop_timed_wait_full (loop=0x555557711800, abstime=abstime@entry=0x7fffffffd7a0)
    at ../src/pipewire/thread-loop.c:442
#6  0x00007fffe3ef94d9 in wait_started (this=0x555557c71ce0) at ../src/gst/gstpipewiresrc.c:722
#7  gst_pipewire_src_change_state (element=0x555557c71ce0, transition=<optimized out>) at ../src/gst/gstpipewiresrc.c:1350
#8  0x00007ffff01fc34e in gst_element_change_state
    (element=element@entry=0x555557c71ce0, transition=transition@entry=GST_STATE_CHANGE_READY_TO_PAUSED) at ../gst/gstelement.c:3083
#9  0x00007ffff01fca8d in gst_element_set_state_func (element=0x555557c71ce0, state=GST_STATE_PLAYING) at ../gst/gstelement.c:3037
#10 0x00007ffff01d952c in gst_bin_element_set_state
    (next=GST_STATE_PLAYING, current=GST_STATE_PLAYING, start_time=0, base_time=31686361031340, element=0x555557c71ce0, bin=0x555555dfab30)
    at ../gst/gstbin.c:2581
#11 gst_bin_change_state_func (element=0x555555dfab30, transition=GST_STATE_CHANGE_PLAYING_TO_PLAYING) at ../gst/gstbin.c:2923
#12 0x00007ffff0226d82 in gst_pipeline_change_state (element=0x555555dfab30, transition=GST_STATE_CHANGE_PLAYING_TO_PLAYING)
    at ../gst/gstpipeline.c:529
#13 0x00007ffff01fc34e in gst_element_change_state
    (element=element@entry=0x555555dfab30, transition=transition@entry=GST_STATE_CHANGE_PLAYING_TO_PLAYING) at ../gst/gstelement.c:3083
#14 0x00007ffff01fca8d in gst_element_set_state_func (element=0x555555dfab30, state=GST_STATE_PLAYING) at ../gst/gstelement.c:3037
#15 0x00007ffff0441a7c in dino_plugins_rtp_plugin_unpause (self=0x5555559a55b0) at ./plugins/rtp/src/plugin.vala:40
#16 0x00007ffff044790f in dino_plugins_rtp_stream_real_create (base=0x555557bfcba0) at ./plugins/rtp/src/stream.vala:160
#17 0x00007ffff7e0faae in xmpp_xep_jingle_rtp_parameters_real_accept
    (base=0x7fffc0005630, stream=<optimized out>, session=<optimized out>, content=<optimized out>)
    at ./xmpp-vala/src/module/xep/0167_jingle_rtp/content_parameters.vala:153
#18 0x00007ffff7e0ec6e in xmpp_xep_jingle_rtp_parameters_real_handle_accept
    (base=0x7fffc0005630, stream=0x55555651edc0, session=0x55555758a210, content=0x555557658100, description_node=<optimized out>) at ./xmpp-vala/src/module/xep/0167_jingle_rtp/content_parameters.vala:183
#19 0x00007ffff7df94f1 in xmpp_xep_jingle_content_handle_accept (self=self@entry=0x555557658100, stream=0x55555651edc0, content_node=content_node@entry=0x555557b9f230) at ./xmpp-vala/src/module/xep/0166_jingle/content.vala:148
#20 0x00007ffff7e07092 in xmpp_xep_jingle_session_handle_content_accept (self=self@entry=0x55555758a210, content_node=content_node@entry=0x555557b9f230, error=0x7fffffffdcd0, error@entry=<error reading variable: Cannot access memory at address 0x7fffffffdca8>) at ./xmpp-vala/src/module/xep/0166_jingle/session.vala:238
#21 0x00007ffff7e0bf94 in xmpp_xep_jingle_session_handle_session_accept (error=0x7fffffffdcc8, iq=0x555556130600, jingle=<optimized out>, content_nodes=0x555557a9b9a0, self=0x55555758a210) at ./xmpp-vala/src/module/xep/0166_jingle/session.vala:267
#22 xmpp_xep_jingle_session_handle_iq_set (self=0x55555758a210, action=<optimized out>, jingle=<optimized out>, iq=0x555556130600, error=error@entry=0x555555e49ce8) at ./xmpp-vala/src/module/xep/0166_jingle/session.vala:62
#23 0x00007ffff7e055c3 in xmpp_xep_jingle_module_handle_iq_set_co (_data_=0x555555e49af0) at ./xmpp-vala/src/module/xep/0166_jingle/jingle_module.vala:220
#24 0x00007ffff6c9d6a9 in g_task_return_now (task=task@entry=0x555555eec0d0) at ../../../gio/gtask.c:1232
#25 0x00007ffff6c9d6e9 in complete_in_idle_cb (task=0x555555eec0d0) at ../../../gio/gtask.c:1246
#26 0x00007ffff6aa55ff in g_main_dispatch (context=0x5555556b71b0) at ../../../glib/gmain.c:3444
#27 g_main_context_dispatch (context=context@entry=0x5555556b71b0) at ../../../glib/gmain.c:4162
#28 0x00007ffff6aa59b8 in g_main_context_iterate (context=context@entry=0x5555556b71b0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4238
#29 0x00007ffff6aa5a4c in g_main_context_iteration (context=context@entry=0x5555556b71b0, may_block=may_block@entry=1) at ../../../glib/gmain.c:4303
#30 0x00007ffff6cccdcd in g_application_run (application=application@entry=0x5555557d3130, argc=<optimized out>, argv=<optimized out>) at ../../../gio/gapplication.c:2571
#31 0x000055555558206f in dino_main (args_length1=<optimized out>, args=<optimized out>) at ./main/src/main.vala:22
#32 main (argc=<optimized out>, argv=<optimized out>) at ./main/src/main.vala:9
```

I'm on Debian Bookworm running Dino 0.3.0, and this hang occurs when I try to use a non-default video device, a USB webcam in particular. Please let me know if I can be of further assistance.

**Comment by Gairick52** [comment]
@jscott0 Hey i am beginner in this project can you suggest me beginner friendly issues to contribute to
