### ISSUE TITLE
Dino crashes on start: SQLite error: 19 - NOT NULL constraint failed: mam_catchup.server_jid

### ISSUE THREAD

**Issue by mesonium** [dino/dino#1304]
### Issue
As suggested in https://github.com/dino/dino/issues/1301#issuecomment-1297072661 I have tried the official openSUSE TW version to see if it's also plagued by the libsoup issue. However Dino crashes short after starting it:

```
** (dino:19252): CRITICAL **: 14:30:50.588: insert_builder.vala:77: SQLite error: 19 - NOT NULL constraint failed: mam_catchup.server_jid
fish: Job 1, 'dino' terminated by signal SIGSEGV (Address boundary error)
```

Could this be due to an upgraded DB table since I have used the master version ever since?

### Stacktrace

```
#0  0x00007f9724b1abab in g_slist_last (list=0x143285abd9a4a111 = {...}, list@entry=0x5574585da370 = {...}) at ../glib/gslist.c:834
#1  0x00007f9724b1abef in g_slist_append (list=0x5574585da370 = {...}, data=0x557458949ad0) at ../glib/gslist.c:247
#2  0x00007f9720da2246 in soup_body_input_stream_http2_add_data (size=8156, data=0x7ffc4d30cbe4 "\366\222@9_9\200\254@i*\371\364]\262\213\207K;T\253 \221\270\210A\022 ~\200?T\210\360\t\327\361%)I\326\251\240\206g\343\326\032\023\064}\002\210\301G\367\006Qo}\325\226\262a\301\245\200\301\264\256\215\250T\324\t\204O\201\213\355\371\373\006\257\312", stream=<optimized out>) at ../libsoup/http2/soup-body-input-stream-http2.c:92
#3  on_data_chunk_recv_callback (session=<optimized out>, flags=<optimized out>, stream_id=1, data=0x7ffc4d30cbe4 "\366\222@9_9\200\254@i*\371\364]\262\213\207K;T\253 \221\270\210A\022 ~\200?T\210\360\t\327\361%)I\326\251\240\206g\343\326\032\023\064}\002\210\301G\367\006Qo}\325\226\262a\301\245\200\301\264\256\215\250T\324\t\204O\201\213\355\371\373\006\257\312", len=8156, user_data=0x55745a490b10) at ../libsoup/http2/soup-client-message-io-http2.c:789
#4  0x00007f9720d4e9cd in nghttp2_session_mem_recv (session=0x55745aec82a0, in=0x7ffc4d30ebc0 "\360\326YZtU", in@entry=0x7ffc4d30cbc0 "\021\241\244\331\253\205\062\024|l\350\344C\365\234\265\313\023;\022\032z\n\317\060\365j", inlen=inlen@entry=8192) at /usr/src/debug/nghttp2-1.50.0-1.1.x86_64/lib/nghttp2_session.c:7170
#5  0x00007f9720da310e in io_read (io=0x55745a490b10, blocking=<optimized out>, cancellable=0x0, error=0x7ffc4d30ec00) at ../libsoup/http2/soup-client-message-io-http2.c:411
#6  0x00007f9720da328f in io_read_ready (stream=<optimized out>, io=0x55745a490b10) at ../libsoup/http2/soup-client-message-io-http2.c:437
#7  0x00007f9724afaa50 in g_main_dispatch (context=0x55745755e9b0) at ../glib/gmain.c:3444
#8  g_main_context_dispatch (context=context@entry=0x55745755e9b0) at ../glib/gmain.c:4162
#9  0x00007f9724afae08 in g_main_context_iterate (context=context@entry=0x55745755e9b0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4238
#10 0x00007f9724afae9c in g_main_context_iteration (context=context@entry=0x55745755e9b0, may_block=may_block@entry=1) at ../glib/gmain.c:4303
#11 0x00007f9724d2a3ed in g_application_run (application=application@entry=0x55745767c130 [DinoUiApplication], argc=<optimized out>, argv=<optimized out>) at ../gio/gapplication.c:2571
#12 0x00005574561fa067 in dino_main (args_length1=<optimized out>, args=<optimized out>) at /usr/src/debug/dino-0.3.0/main/src/main.vala:22
#13 main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/dino-0.3.0/main/src/main.vala:9
(gdb) bt full
#0  0x00007f9724b1abab in g_slist_last (list=0x143285abd9a4a111 = {...}, list@entry=0x5574585da370 = {...}) at ../glib/gslist.c:834
#1  0x00007f9724b1abef in g_slist_append (list=0x5574585da370 = {...}, data=0x557458949ad0) at ../glib/gslist.c:247
        new_list = 0x55745abd2e50 = {0x557458949ad0}
        last = <optimized out>
#2  0x00007f9720da2246 in soup_body_input_stream_http2_add_data (size=8156, data=0x7ffc4d30cbe4 "\366\222@9_9\200\254@i*\371\364]\262\213\207K;T\253 \221\270\210A\022 ~\200?T\210\360\t\327\361%)I\326\251\240\206g\343\326\032\023\064}\002\210\301G\367\006Qo}\325\226\262a\301\245\200\301\264\256\215\250T\324\t\204O\201\213\355\371\373\006\257\312", stream=<optimized out>) at ../libsoup/http2/soup-body-input-stream-http2.c:92
        priv = 0x55745a49c400
        io = 0x55745a490b10
        msgdata = 0x55745a579560
        __func__ = "on_data_chunk_recv_callback"
#3  on_data_chunk_recv_callback (session=<optimized out>, flags=<optimized out>, stream_id=1, data=0x7ffc4d30cbe4 "\366\222@9_9\200\254@i*\371\364]\262\213\207K;T\253 \221\270\210A\022 ~\200?T\210\360\t\327\361%)I\326\251\240\206g\343\326\032\023\064}\002\210\301G\367\006Qo}\325\226\262a\301\245\200\301\264\256\215\250T\324\t\204O\201\213\355\371\373\006\257\312", len=8156, user_data=0x55745a490b10) at ../libsoup/http2/soup-client-message-io-http2.c:789
        io = 0x55745a490b10
        msgdata = 0x55745a579560
        __func__ = "on_data_chunk_recv_callback"
#4  0x00007f9720d4e9cd in nghttp2_session_mem_recv (session=0x55745aec82a0, in=0x7ffc4d30ebc0 "\360\326YZtU", in@entry=0x7ffc4d30cbc0 "\021\241\244\331\253\205\062\024|l\350\344C\365\234\265\313\023;\022\032z\n\317\060\365j", inlen=inlen@entry=8192) at /usr/src/debug/nghttp2-1.50.0-1.1.x86_64/lib/nghttp2_session.c:7170
        data_readlen = <optimized out>
        first = 0x7ffc4d30cbc0 "\021\241\244\331\253\205\062\024|l\350\344C\365\234\265\313\023;\022\032z\n\317\060\365j"
        last = 0x7ffc4d30ebc0 "\360\326YZtU"
        iframe = 0x55745aec8578
        readlen = <optimized out>
        padlen = <optimized out>
        rv = <optimized out>
        busy = 0
        cont_hd = {length = 140287134256096, stream_id = 190508040, type = 151 '\227', flags = 127 '\177', reserved = 0 '\000'}
        stream = 0x55745aeae570
        pri_fieldlen = <optimized out>
        mem = 0x55745aec8c80
        __PRETTY_FUNCTION__ = "nghttp2_session_mem_recv"
#5  0x00007f9720da310e in io_read (io=0x55745a490b10, blocking=<optimized out>, cancellable=0x0, error=0x7ffc4d30ec00) at ../libsoup/http2/soup-client-message-io-http2.c:411
        buffer = "\021\241\244\331\253\205\062\024|l\350\344C\365\234\265\313\023;\022\032z\n\317\060\365j\000 \000\000\000\000\000\000\001\366\222@9_9\200\254@i*\371\364]\262\213\207K;T\253 \221\270\210A\022 ~\200?T\210\360\t\327\361%)I\326\251\240\206g\343\326\032\023\064}\002\210\301G\367\006Qo}\325\226\262a\301\245\200\301\264\256\215\250T\324\t\204O\201\213\355\371\373\006\257\312\000\273' =\242\212}\037\354\202\251\270\313\026~\037Nb\276\250p\221>[\233\003\212\216\330\345/\262en\236\034\360\240>\316>\374\303\066\377\n\242}\312\244\000\330\034\244+\256\300}\361\275\245.\267\305\220O\300\301\236O~ +\312\342\263g\370"...
        read = 8192
        ret = <optimized out>
        __func__ = "io_read"
#6  0x00007f9720da328f in io_read_ready (stream=<optimized out>, io=0x55745a490b10) at ../libsoup/http2/soup-client-message-io-http2.c:437
        error = 0x0
        progress = <optimized out>
        conn = 0x55745a59d6f0 [SoupConnection]
#7  0x00007f9724afaa50 in g_main_dispatch (context=0x55745755e9b0) at ../glib/gmain.c:3444
        dispatch = 0x7f9724cdcbe0 <pollable_source_dispatch>
        prev_source = 0x0
        begin_time_nsec = 0
        was_in_call = 0
        user_data = 0x55745a490b10
        callback = 0x7f9720da31f0 <io_read_ready>
        cb_funcs = 0x7f9724bdb2c0 <g_source_callback_funcs>
        cb_data = 0x55745a479fb0
        need_destroy = <optimized out>
        source = 0x55745a98ceb0
        current = 0x557457561110
        i = 2
        __func__ = "g_main_dispatch"
#8  g_main_context_dispatch (context=context@entry=0x55745755e9b0) at ../glib/gmain.c:4162
#9  0x00007f9724afae08 in g_main_context_iterate (context=context@entry=0x55745755e9b0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4238
        max_priority = 0
        timeout = 0
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = 9
        fds = 0x55745a4b4e40
#10 0x00007f9724afae9c in g_main_context_iteration (context=context@entry=0x55745755e9b0, may_block=may_block@entry=1) at ../glib/gmain.c:4303
        retval = <optimized out>
#11 0x00007f9724d2a3ed in g_application_run (application=application@entry=0x55745767c130 [DinoUiApplication], argc=<optimized out>, argv=<optimized out>) at ../gio/gapplication.c:2571
        arguments = 0x55745768d030
        status = 0
        context = 0x55745755e9b0
        acquired_context = <optimized out>
        __func__ = "g_application_run"
#12 0x00005574561fa067 in dino_main (args_length1=<optimized out>, args=<optimized out>) at /usr/src/debug/dino-0.3.0/main/src/main.vala:22
        _tmp3_ = 0x557457541c50 "dino"
        _tmp7_ = 0x0
        app = 0x55745767c130 [DinoUiApplication]
        _tmp13_ = 0x557457749e20 [DinoPluginsLoader]
        _tmp2_ = 0x557457541c50 "dino"
        _tmp6_ = <optimized out>
        _tmp12_ = 0x557457749e20 [DinoPluginsLoader]
        exec_path = 0x557457541c50 "dino"
        _tmp5_ = 0x557457542e10 [DinoSearchPathGenerator]
        _tmp9_ = <optimized out>
        _tmp11_ = 0x55745767c130 [DinoUiApplication]
        _tmp15_ = <optimized out>
        _tmp0_ = <optimized out>
        search_path_generator = 0x557457542e10 [DinoSearchPathGenerator]
        _tmp4_ = 0x557457542e10 [DinoSearchPathGenerator]
        _tmp8_ = 0x557457542e10 [DinoSearchPathGenerator]
        _tmp10_ = 0x55745767c130 [DinoUiApplication]
        loader = 0x557457749e20 [DinoPluginsLoader]
        _tmp14_ = 0x55745767c130 [DinoUiApplication]
        _inner_error0_ = 0x0
#13 main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/dino-0.3.0/main/src/main.vala:9
```

### Setup
* Version        : 0.3.0-3.1
* Installed from openSUSE TW Repo

**Comment by jubalh** [comment]
> Could this be due to an upgraded DB table since I have used the master version ever since?

Looks like it.
And such stuff is usually als not supported.

If you use the regular TW package for dino and haven't used git master before then I don't get this.

**Comment by mesonium** [comment]
Let's close it; I will test it with a new profile.
