### ISSUE TITLE
Crash on startup: ui_util_summarize_whitespaces_to_space: code should not be reached

### ISSUE THREAD

**Issue by truenicoco** [dino/dino#1335]
Using `0.3.0~git63.20230107.424a429-1` on debian testing. I cannot launch dino anymore:

```
**
dino:ERROR:./main/src/ui/util/helper.vala:422:dino_ui_util_summarize_whitespaces_to_space: code should not be reached
Bail out! dino:ERROR:./main/src/ui/util/helper.vala:422:dino_ui_util_summarize_whitespaces_to_space: code should not be reached
Aborted
```

Since I was trying to see if https://github.com/dino/dino/issues/1296 worked for me and figured maybe internal DB breaking changes were made, I tried with a clean profile (ie, after `rm ~/.local/share/dino -rf`). Dino can start, but I experience the same crash when during MAM fetching when I re-add my account. After this initial crash, dino instantly crash on attempt to relaunch.

I did the "`rm ~/.local/share/dino -rf`, re-add account" dance a few times with `print-xmpp=message` and it seems to happen consistently after these:

```xml
XMPP IN [nicoco@slidge.im stream:0x55ac51b8a680 thread:0x55ac51660810 2023-01-08T11:22:55+0100]
<message id='316040806400' to='nicoco@slidge.im/dino.be563003' lang='en' from='group-1001318977944@telegram.slidge.im/Moon Knight' type='groupchat'>
  <body>
    i app pinned, now stuck at one app only😐
  </body>
  <markable xmlns='urn:xmpp:chat-markers:0' />
  <stanza-id id='316040806400' by='group-1001318977944@telegram.slidge.im' xmlns='urn:xmpp:sid:0' />
  <delay from='telegram.slidge.im' stamp='2023-01-07T18:30:35Z' xmlns='urn:xmpp:delay' />
</message>

XMPP IN [nicoco@slidge.im stream:0x55ac51b8a680 thread:0x55ac51660810 2023-01-08T11:22:55+0100]
<message id='316041854976' to='nicoco@slidge.im/dino.be563003' lang='en' from='group-1001318977944@telegram.slidge.im/A man' type='groupchat'>
  <body>
    > i app pinned, now stuck at one app only😐    
Gesture navigation?
  </body>
  <markable xmlns='urn:xmpp:chat-markers:0' />
  <stanza-id id='316041854976' by='group-1001318977944@telegram.slidge.im' xmlns='urn:xmpp:sid:0' />
  <delay from='telegram.slidge.im' stamp='2023-01-07T18:31:07Z' xmlns='urn:xmpp:delay' />
  <reply id='316040806400' to='group-1001318977944@telegram.slidge.im/Moon Knight' xmlns='urn:xmpp:reply:0' />
  <fallback for='urn:xmpp:reply:0' xmlns='urn:xmpp:fallback:0'>
    <body start='0' end='42' />
  </fallback>
</message>
```

**Comment by fiaxh** [comment]
The issue is that for whatever reason, a method call that we did not expect to fail fails. The question is: why? Unfortunately we didn't print the error so far.

I pushed 73c0263f35a73b68d20d299ee7fe8c37b9a6ffeb to master. The commit makes Dino not crash anymore, instead there should be a CRITICAL log starting with "RegexError when summarizing whitespaces [...]". Can you please retest and tell me what it says?

**Comment by truenicoco** [comment]
I updated from the opensuse repos in my debian bookworm VM. Your latest commit hasn't reached it yet, but I gave it a try anyway (was curious if the issue still occured…) and now hit:

```
LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!
```

on startup (which exits). I'll try again later with the latest commit but I suspect this new error won't be fixed by difference between 860c72b and https://github.com/dino/dino/commit/73c0263f35a73b68d20d299ee7fe8c37b9a6ffeb

**Comment by truenicoco** [comment]
Just tried again in my debian testing QEMU VM and got a gdb trace out of it in case you guys are interested:

```
Starting program: /usr/bin/dino 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff37fd6c0 (LWP 17298)]
[Thread 0x7ffff37fd6c0 (LWP 17298) exited]
[New Thread 0x7ffff37fd6c0 (LWP 17299)]
[New Thread 0x7ffff09bd6c0 (LWP 17300)]
[New Thread 0x7fffe35ff6c0 (LWP 17301)]
[New Thread 0x7fffe2dfe6c0 (LWP 17302)]
[New Thread 0x7fffe166c6c0 (LWP 17303)]
[New Thread 0x7fffd3fff6c0 (LWP 17304)]
[New Thread 0x7fffd3fff6c0 (LWP 17305)]
[Thread 0x7fffd3fff6c0 (LWP 17304) exited]
[New Thread 0x7fffd37fe6c0 (LWP 17306)]
[New Thread 0x7fffd2ffd6c0 (LWP 17307)]
[Thread 0x7fffd37fe6c0 (LWP 17306) exited]
[New Thread 0x7fffd37fe6c0 (LWP 17308)]
[Thread 0x7fffd2ffd6c0 (LWP 17307) exited]
[New Thread 0x7fffd2ffd6c0 (LWP 17309)]
[Thread 0x7fffd37fe6c0 (LWP 17308) exited]
[New Thread 0x7fffd37fe6c0 (LWP 17310)]
[Thread 0x7fffd2ffd6c0 (LWP 17309) exited]
[New Thread 0x7fffd2ffd6c0 (LWP 17311)]
[Thread 0x7fffd37fe6c0 (LWP 17310) exited]
[Thread 0x7fffd2ffd6c0 (LWP 17311) exited]
[New Thread 0x7fffd2ffd6c0 (LWP 17312)]
[New Thread 0x7fffd37fe6c0 (LWP 17313)]
[New Thread 0x7fffc3fff6c0 (LWP 17314)]
[New Thread 0x7fffc37fe6c0 (LWP 17315)]
[New Thread 0x7fffc2ffd6c0 (LWP 17316)]
[New Thread 0x7fffc27fc6c0 (LWP 17317)]
[New Thread 0x7fffc1ffb6c0 (LWP 17318)]
[New Thread 0x7fffc17fa6c0 (LWP 17319)]
[New Thread 0x7fffc0ff96c0 (LWP 17320)]
[New Thread 0x7fffb7fff6c0 (LWP 17321)]
[New Thread 0x7fffb77fe6c0 (LWP 17322)]
[Thread 0x7fffb7fff6c0 (LWP 17321) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17323)]
[Thread 0x7fffb77fe6c0 (LWP 17322) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17324)]
[Thread 0x7fffb7fff6c0 (LWP 17323) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17325)]
[Thread 0x7fffb77fe6c0 (LWP 17324) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17326)]
[Thread 0x7fffb7fff6c0 (LWP 17325) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17327)]
[Thread 0x7fffb77fe6c0 (LWP 17326) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17328)]
[Thread 0x7fffb7fff6c0 (LWP 17327) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17329)]
[Thread 0x7fffb77fe6c0 (LWP 17328) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17330)]
[Thread 0x7fffb7fff6c0 (LWP 17329) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17331)]
[Thread 0x7fffb77fe6c0 (LWP 17330) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17332)]
[Thread 0x7fffb7fff6c0 (LWP 17331) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17333)]
[Thread 0x7fffb77fe6c0 (LWP 17332) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17334)]
[Thread 0x7fffb7fff6c0 (LWP 17333) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17335)]
[Thread 0x7fffb77fe6c0 (LWP 17334) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17336)]
[Thread 0x7fffb7fff6c0 (LWP 17335) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17337)]
[Thread 0x7fffb77fe6c0 (LWP 17336) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17338)]
[Thread 0x7fffb7fff6c0 (LWP 17337) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17339)]
[Thread 0x7fffb77fe6c0 (LWP 17338) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17340)]
[Thread 0x7fffb7fff6c0 (LWP 17339) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17341)]
[Thread 0x7fffb77fe6c0 (LWP 17340) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17342)]
[Thread 0x7fffb7fff6c0 (LWP 17341) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17343)]
[Thread 0x7fffb77fe6c0 (LWP 17342) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17344)]
[Thread 0x7fffb7fff6c0 (LWP 17343) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17345)]
[Thread 0x7fffb77fe6c0 (LWP 17344) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17346)]
[Thread 0x7fffb7fff6c0 (LWP 17345) exited]
[New Thread 0x7fffb7fff6c0 (LWP 17347)]
[Thread 0x7fffb77fe6c0 (LWP 17346) exited]
[New Thread 0x7fffb77fe6c0 (LWP 17348)]
[Thread 0x7fffb7fff6c0 (LWP 17347) exited]
[Thread 0x7fffb77fe6c0 (LWP 17348) exited]

Thread 1 "dino" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
44      ./nptl/pthread_kill.c: No such file or directory.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
    at ./nptl/pthread_kill.c:44
#1  0x00007ffff686fd2f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff6820ef2 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff680b472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007fffe5c8bbeb in llvm::report_fatal_error(llvm::Twine const&, bool) () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#5  0x00007fffe5c8ba36 in  () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#6  0x00007fffe88f158b in  () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#7  0x00007fffe88f182a in  () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#8  0x00007fffe88f2f1e in  () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#9  0x00007fffe88f3085 in  () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#10 0x00007fffe790e68d in  () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#11 0x00007fffe72d2bee in llvm::TargetIRAnalysis::run(llvm::Function const&, llvm::AnalysisManager<llvm::Function>&) ()
    at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#12 0x00007fffe682f0fb in  () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#13 0x00007fffe5ed1530 in llvm::AnalysisManager<llvm::Function>::getResultImpl(llvm::AnalysisKey*, llvm::Function&) ()
    at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#14 0x00007fffe7081f39 in llvm::AssumptionAnalysis::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) ()
    at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#15 0x00007fffe682da51 in  () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#16 0x00007fffe5ed1530 in llvm::AnalysisManager<llvm::Function>::getResultImpl(llvm::AnalysisKey*, llvm::Function&) ()
    at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#17 0x00007fffe6cfc3da in llvm::SROAPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) ()
    at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#18 0x00007fffe8ae2ded in  () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#19 0x00007fffe5eceea9 in llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#20 0x00007fffe7c21bad in  () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#21 0x00007fffe5ed2cf1 in llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) ()
    at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#22 0x00007fffe7c219cd in  () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#23 0x00007fffe5ecdad9 in llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#24 0x00007fffe8aff03b in LLVMRunPasses () at /lib/x86_64-linux-gnu/libLLVM-15.so.1
#25 0x00007ffff1070cc7 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#26 0x00007ffff10e9096 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#27 0x00007ffff10d9f38 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#28 0x00007ffff10be298 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#29 0x00007ffff0c6af15 in  () at /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
#30 0x00007ffff72b3b52 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#31 0x00007ffff72cd883 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#32 0x00007ffff72ad08c in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#33 0x00007ffff72950da in gsk_renderer_render () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#34 0x00007ffff7113959 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#35 0x00007ffff711af35 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#36 0x00007ffff720f594 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#37 0x00007ffff76fc5a9 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#38 0x00007ffff771505e in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#39 0x00007ffff7715dbf in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#40 0x00007ffff7289013 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#41 0x00007ffff76fc5a9 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#42 0x00007ffff7715bbf in g_signal_emit_valist () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#43 0x00007ffff7715dbf in g_signal_emit () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#44 0x00007ffff7278e05 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#45 0x00007ffff7279a0e in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#46 0x00007ffff7279af4 in  () at /lib/x86_64-linux-gnu/libgtk-4.so.1
#47 0x00007ffff6a1b19a in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#48 0x00007ffff6a1a67f in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#49 0x00007ffff6a1aa38 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#50 0x00007ffff6a1aacc in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#51 0x00007ffff6bdb65d in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#52 0x0000555555581e67 in dino_main (args_length1=1, args=0x7fffffffe4c8) at ./main/src/main.vala:22
#53 main (argc=1, argv=0x7fffffffe4c8) at ./main/src/main.vala:9

quit
```

**Comment by truenicoco** [comment]
So, I can't reproduce the initial bug anymore, and I'm getting the LLVM thing even with 0.4.0 release on my QEMU VM.

I tried 0.4.0 on debian bookworm on a non-virtual laptop and it works just fine. Sorry I couldn't investigate the initial bug more... :(
