### ISSUE TITLE
Crashes with SIGABRT on every launch

### ISSUE THREAD

**Issue by bascht** [dino/dino#137]
Heya. I somehow managed to break my dino. 😸 It will crash with

```
./build/dino 

(dino:18142): GLib-CRITICAL **: g_rand_int_range: assertion 'end > begin' failed
**
ERROR:arraylist.c:957:gee_array_list_real_get: assertion failed: (index < _size)
fish: “./build/dino” terminated by signal SIGABRT (Abort)
command failed with status: 134
```

I've run it via `gdb ./build/dino` but I'm not sure if that backtrace will help:

```
#0  0x00007f9f4b28369b in raise () at /lib64/libc.so.6
#1  0x00007f9f4b2854a0 in abort () at /lib64/libc.so.6
#2  0x00007f9f4b68e70d in g_assertion_message () at /lib64/libglib-2.0.so.0
#3  0x00007f9f4b68e79a in g_assertion_message_expr () at /lib64/libglib-2.0.so.0
#4  0x00007f9f4e10aa59 in gee_array_list_real_get () at /lib64/libgee-0.8.so.2
#5  0x00007f9f3738399a in dino_plugins_omemo_stream_module_on_other_bundle_result (self=0x7b0ef0, stream=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, jid=0x7f9f2813b590 "friend@myserver.com", device_id=98220780, id=0x7f9f2813b570 "1", node=0x7f9f2813a280) at /home/bascht/Documents/Code/dino/plugins/omemo/src/stream_module.vala:286
#6  0x00007f9f37382cce in ___lambda6_ (_data1_=0x8b6e60, stream=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, jid=0x7f9f2813b590 "friend@myserver.com", id=0x7f9f2813b570 "1", node=0x7f9f2813a280) at /home/bascht/Documents/Code/dino/plugins/omemo/src/stream_module.vala:245
#7  0x00007f9f37382d0b in ____lambda6__xmpp_xep_pubsub_module_on_result (stream=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, jid=0x7f9f2813b590 "friend@myserver.com", id=0x7f9f2813b570 "1", node=0x7f9f2813a280, self=0x8b6e60) at /home/bascht/Documents/Code/dino/plugins/omemo/src/stream_module.vala:244
#8  0x00007f9f4e64d2d2 in __lambda21_ (_data15_=0x7f9f280b3ca0, stream=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, iq=0x7f9f28158a50) at /home/bascht/Documents/Code/dino/xmpp-vala/src/module/xep/0060_pubsub.vala:28
#9  0x00007f9f4e64d3cf in ___lambda21__xmpp_iq_module_on_result (stream=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, iq=0x7f9f28158a50, self=0x7f9f280b3ca0) at /home/bascht/Documents/Code/dino/xmpp-vala/src/module/xep/0060_pubsub.vala:23
#10 0x00007f9f4e61d6a1 in xmpp_iq_module_on_received_iq_stanza (self=0x94b850, stream=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, node=0x7f9f2813d1e0) at /home/bascht/Documents/Code/dino/xmpp-vala/src/module/iq/module.vala:55
#11 0x00007f9f4e61d07e in _xmpp_iq_module_on_received_iq_stanza_xmpp_core_xmpp_stream_received_iq_stanza (_sender=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, stream=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, node=0x7f9f2813d1e0, self=0x94b850) at /home/bascht/Documents/Code/dino/xmpp-vala/src/module/iq/module.vala:34
#12 0x00007f9f4e6172bf in g_cclosure_user_marshal_VOID__XMPP_CORE_XMPP_STREAM_XMPP_CORE_STANZA_ENTRY (closure=0x7f9f28000900, return_value=0x0, n_param_values=3, param_values=0x7f9f3527f490, invocation_hint=0x7f9f3527f410, marshal_data=0x0) at /home/bascht/Documents/Code/dino/xmpp-vala/src/core/xmpp_stream.vala:13
#13 0x00007f9f4b94030d in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#14 0x00007f9f4b95298e in signal_emit_unlocked_R () at /lib64/libgobject-2.0.so.0
#15 0x00007f9f4b95b1a5 in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#16 0x00007f9f4b95bb0f in g_signal_emit () at /lib64/libgobject-2.0.so.0
#17 0x00007f9f4e616009 in xmpp_core_xmpp_stream_loop (self=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, error=0x7f9f3527f8d8) at /home/bascht/Documents/Code/dino/xmpp-vala/src/core/xmpp_stream.vala:213
#18 0x00007f9f4e61387a in xmpp_core_xmpp_stream_connect (self=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, remote_name=0x850ad0 "myserver.com", error=0x7f9f3527faa0) at /home/bascht/Documents/Code/dino/xmpp-vala/src/core/xmpp_stream.vala:70
#19 0x00007f9f4eac4d6a in __lambda9_ (_data2_=0x885280) at /home/bascht/Documents/Code/dino/libdino/src/service/connection_manager.vala:138
#20 0x00007f9f4eac5070 in ___lambda9__gthread_func (self=0x885280) at connection_manager.c:1041
#21 0x00007f9f4b68f536 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#22 0x00007f9f4abbe36d in start_thread () at /lib64/libpthread.so.0
#23 0x00007f9f4b35dbbf in clone () at /lib64/libc.so.6
```

Tested under Fedora 26.
```
GTK 3.22.18-1
Vala 0.36.4-1
```
Let me know if I can supply more information.

**Comment by bascht** [comment]
Wow, that was really quick. Thanks for the fix, dino starts again. 🎉
