### ISSUE TITLE
Dino SEGFAULTs shortly after startup

### ISSUE THREAD

**Issue by WhyNotHugo** [dino/dino#1378]
On the first run, `dino` prompted me for credentials, I logged in, and it SEGFAULTed a second or two afterwards.

Trying to run `dino` now SEGFAULTs after starting (it starts rendering, and then within a second or two segfaults).

If I delete `.local/share/dino` it works again, but after I log in, it crashes again and I'm back in the same situation.

Originally [reported downstream](https://gitlab.alpinelinux.org/alpine/aports/-/issues/14662), but it doesn't seem to be an Alpine-specific issue.

Backtrace:

```
#0  0x00007ffff7dd8830 in xmpp_message_archive_management_NS_VER (stream=0x7fffde27cba0 [XmppStartTlsXmppStream])
    at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/xmpp-vala/src/module/xep/0313_message_archive_management.vala:159
#1  0x00007ffff7dd8905 in xmpp_message_archive_management_create_base_query
    (stream=stream@entry=0x7fffde27cba0 [XmppStartTlsXmppStream], ns=ns@entry=0x7ffff7e0cbd0 "urn:xmpp:mam:2", queryid=0x7fffeb1cf9e0 "85c73392-9f7e-43fa-aa99-9706f7e01aaf", fields=fields@entry=0x7fffeb1e0be0)
    at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/xmpp-vala/src/module/xep/0313_message_archive_management.vala:60
#2  0x00007ffff7dd9ff1 in xmpp_message_archive_management_v2_create_base_query (stream=0x7fffde27cba0 [XmppStartTlsXmppStream], mam_params=0x7ffff44b2590 [XmppMessageArchiveManagementV2MamQueryParams])
    at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/xmpp-vala/src/module/xep/0313_2_message_archive_management.vala:61
#3  0x00007ffff7dda1c2 in xmpp_message_archive_management_v2_query_archive_co (_data_=0x7fffd9fa2320) at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/xmpp-vala/src/module/xep/0313_2_message_archive_management.vala:65
#4  0x00007ffff7edbe82 in dino_history_sync_fetch_latest_page_co (_data_=0x7fffda2a6c10) at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/libdino/src/service/history_sync.vala:210
#5  0x00007ffff7edd36c in dino_history_sync_fetch_latest_page
    (self=<optimized out>, account=<optimized out>, mam_server=<optimized out>, latest_row=0x7fffffffcde0, until_earliest_time=<optimized out>, cancellable=0x7ffff7edbe82, _callback_=<optimized out>, _user_data_=<optimized out>)
    at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/libdino/src/service/history_sync.vala:8
#6  0x00007ffff7edd8af in dino_history_sync_fetch_everything_co (_data_=0x7fffeb1f2e50) at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/libdino/src/service/history_sync.vala:135
#7  0x00007ffff7edefa8 in dino_history_sync_fetch_everything
    (self=<optimized out>, account=<optimized out>, mam_server=<optimized out>, cancellable=0x7fffeb18c3f0 [GCancellable], until_earliest_time=<optimized out>, _callback_=0x7ffff7ef3360 <_______lambda94__gasync_ready_callback>, _user_data_=<optimized out>)
    at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/libdino/src/service/history_sync.vala:8
#8  0x00007ffff7ef64b3 in dino_muc_manager_join_co (_data_=0x7fffd8162490) at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/libdino/src/service/muc_manager.vala:117
#9  0x00007ffff6ed21b3 in g_task_return_now (task=task@entry=0x7ffff4a5cd90 [GTask]) at ../gio/gtask.c:1232
#10 0x00007ffff6ed2b93 in g_task_return (type=<optimized out>, task=0x7ffff4a5cd90 [GTask]) at ../gio/gtask.c:1301
#11 g_task_return (task=0x7ffff4a5cd90 [GTask], type=<optimized out>) at ../gio/gtask.c:1258
#12 0x00007ffff7d7acf4 in xmpp_xep_muc_module_enter_co (_data_=0x7fffeb268d40) at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/xmpp-vala/src/module/xep/0045_muc/module.vala:119
#13 0x00007ffff6ed21b3 in g_task_return_now (task=task@entry=0x7fffea55b0d0 [GTask]) at ../gio/gtask.c:1232
#14 0x00007ffff6ed2b93 in g_task_return (type=<optimized out>, task=0x7fffea55b0d0 [GTask]) at ../gio/gtask.c:1301
#15 g_task_return (task=0x7fffea55b0d0 [GTask], type=<optimized out>) at ../gio/gtask.c:1258
#16 0x00007ffff7c73a28 in  () at /usr/lib/libgee-0.8.so.2
#17 0x00007ffff7c73fe7 in gee_promise_set_value () at /usr/lib/libgee-0.8.so.2
#18 0x00007ffff7d79c07 in xmpp_xep_muc_module_on_received_available (presence=0x7fffd817f600 [XmppPresenceStanza], stream=0x7fffde27cba0 [XmppStartTlsXmppStream], self=0x7ffff44ab2d0 [XmppXepMucModule])
    at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/xmpp-vala/src/module/xep/0045_muc/module.vala:361
#19 _xmpp_xep_muc_module_on_received_available_xmpp_presence_module_received_available (_sender=<optimized out>, stream=0x7fffde27cba0 [XmppStartTlsXmppStream], presence=0x7fffd817f600 [XmppPresenceStanza], self=0x7ffff44ab2d0)
    at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/xmpp-vala/src/module/xep/0045_muc/module.vala:260
#23 0x00007ffff6df3e9f in <emit signal ??? on instance 0x7ffff4488ab0 [XmppPresenceModule]> (instance=instance@entry=0x7ffff4488ab0, signal_id=<optimized out>, detail=detail@entry=0) at ../gobject/gsignal.c:3606
    #20 0x00007ffff6dda430 in g_closure_invoke (closure=0x7fffeb1fc570, return_value=return_value@entry=0x0, n_param_values=3, param_values=param_values@entry=0x7fffffffd1e0, invocation_hint=invocation_hint@entry=0x7fffffffd160) at ../gobject/gclosure.c:832
    #21 0x00007ffff6ded4c6 in signal_emit_unlocked_R (node=node@entry=0x7ffff44a7be0, detail=detail@entry=0, instance=instance@entry=0x7ffff4488ab0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffd1e0)
    at ../gobject/gsignal.c:3796
    #22 0x00007ffff6df3cbe in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd390) at ../gobject/gsignal.c:3549
#24 0x00007ffff7d5c504 in xmpp_presence_module_on_received_presence_stanza (node=<optimized out>, stream=0x7fffde27cba0 [XmppStartTlsXmppStream], self=0x7ffff4488ab0 [XmppPresenceModule])
    at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/xmpp-vala/src/module/presence/module.vala:75
#25 _xmpp_presence_module_on_received_presence_stanza_xmpp_xmpp_stream_received_presence_stanza (_sender=<optimized out>, stream=0x7fffde27cba0 [XmppStartTlsXmppStream], node=<optimized out>, self=0x7ffff4488ab0)
    at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/xmpp-vala/src/module/presence/module.vala:60
#29 0x00007ffff6df3e9f in <emit signal ??? on instance 0x7fffde27cba0 [XmppStartTlsXmppStream]> (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3606
    #26 0x00007ffff6dda430 in g_closure_invoke (closure=0x7ffff48c9370, return_value=return_value@entry=0x0, n_param_values=3, param_values=param_values@entry=0x7fffffffd650, invocation_hint=invocation_hint@entry=0x7fffffffd5d0) at ../gobject/gclosure.c:832
    #27 0x00007ffff6ded4c6 in signal_emit_unlocked_R (node=node@entry=0x7ffff368fc10, detail=detail@entry=0, instance=instance@entry=0x7fffde27cba0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffd650)
    at ../gobject/gsignal.c:3796
    #28 0x00007ffff6df3cbe in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd800) at ../gobject/gsignal.c:3549
#30 0x00007ffff7d45d9c in xmpp_xmpp_stream_handle_stanza_co (_data_=0x7fffeb1d7e20) at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/xmpp-vala/src/core/xmpp_stream.vala:149
#31 0x00007ffff7d4619f in xmpp_xmpp_stream_handle_stanza (_callback_=0x7ffff7d465f7 <xmpp_xmpp_stream_loop_ready>, _user_data_=<optimized out>, node=<optimized out>, self=0x7fffde27cba0 [XmppStartTlsXmppStream])
    at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/xmpp-vala/src/core/xmpp_stream.vala:3
#32 xmpp_xmpp_stream_loop_co (_data_=<optimized out>) at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/xmpp-vala/src/core/xmpp_stream.vala:113
#33 0x00007ffff6cdfbaf in g_main_dispatch (context=0x7ffff63bdeb0) at ../glib/gmain.c:3454
#34 g_main_context_dispatch (context=0x7ffff63bdeb0) at ../glib/gmain.c:4172
#35 0x00007ffff6cdff68 in g_main_context_iterate (context=context@entry=0x7ffff63bdeb0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4248
#36 0x00007ffff6cdfffc in g_main_context_iteration (context=context@entry=0x7ffff63bdeb0, may_block=may_block@entry=1) at ../glib/gmain.c:4313
#37 0x00007ffff6effc1d in g_application_run (application=application@entry=0x7ffff4c77f70 [DinoUiApplication], argc=argc@entry=1, argv=argv@entry=0x7fffffffdb78) at ../gio/gapplication.c:2573
#38 0x0000555555582d98 in dino_main (args_length1=1, args=0x7fffffffdb78) at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/main/src/main.vala:22
#39 main (argc=1, argv=0x7fffffffdb78) at /home/hugo/clones/gitlab.alpinelinux.org/alpine/aports/community/dino/src/dino-0.4.0/main/src/main.vala:9
```

This is 0.4.0 from Alpine aports. [There are no distro-specific patches or anything out of the ordinary in its build](https://gitlab.alpinelinux.org/alpine/aports/-/blob/master/community/dino/APKBUILD).

**Comment by WhyNotHugo** [comment]
Oh, I realise that 0.4.1 is out. I tried it also SEGFAULTs. Here's the backtrace for 0.4.1:

```
Thread 1 "dino" received signal SIGSEGV, Segmentation fault.
0x00007ffff7dd903c in xmpp_message_archive_management_NS_VER () from /usr/lib/libxmpp-vala.so.0
(gdb) bt
#0  0x00007ffff7dd903c in xmpp_message_archive_management_NS_VER () at /usr/lib/libxmpp-vala.so.0
#1  0x00007ffff7dd9111 in xmpp_message_archive_management_create_base_query () at /usr/lib/libxmpp-vala.so.0
#2  0x00007ffff7dda7fd in xmpp_message_archive_management_v2_create_base_query () at /usr/lib/libxmpp-vala.so.0
#3  0x00007ffff7dda9ce in  () at /usr/lib/libxmpp-vala.so.0
#4  0x00007ffff7edbea1 in  () at /usr/lib/libdino.so.0
#5  0x00007ffff7edd8ce in  () at /usr/lib/libdino.so.0
#6  0x00007ffff7ef64f5 in  () at /usr/lib/libdino.so.0
#7  0x00007ffff6ed21b3 in g_task_return_now (task=task@entry=0x7fffd990f850 [GTask]) at ../gio/gtask.c:1232
#8  0x00007ffff6ed2b93 in g_task_return (type=<optimized out>, task=0x7fffd990f850 [GTask]) at ../gio/gtask.c:1301
#9  g_task_return (task=0x7fffd990f850 [GTask], type=<optimized out>) at ../gio/gtask.c:1258
#10 0x00007ffff7d7bcd4 in  () at /usr/lib/libxmpp-vala.so.0
#11 0x00007ffff6ed21b3 in g_task_return_now (task=task@entry=0x7fffd9f32310 [GTask]) at ../gio/gtask.c:1232
#12 0x00007ffff6ed2b93 in g_task_return (type=<optimized out>, task=0x7fffd9f32310 [GTask]) at ../gio/gtask.c:1301
#13 g_task_return (task=0x7fffd9f32310 [GTask], type=<optimized out>) at ../gio/gtask.c:1258
#14 0x00007ffff7c74a28 in  () at /usr/lib/libgee-0.8.so.2
#15 0x00007ffff7c74fe7 in gee_promise_set_value () at /usr/lib/libgee-0.8.so.2
#16 0x00007ffff7d7abe7 in  () at /usr/lib/libxmpp-vala.so.0
#20 0x00007ffff6df3e9f in <emit signal ??? on instance 0x7ffff445d180 [XmppPresenceModule]> (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3606
    #17 0x00007ffff6dda430 in g_closure_invoke (closure=0x7fffecafe970, return_value=return_value@entry=0x0, n_param_values=3, param_values=param_values@entry=0x7fffffffd1e0, invocation_hint=invocation_hint@entry=0x7fffffffd160) at ../gobject/gclosure.c:832
    #18 0x00007ffff6ded4c6 in signal_emit_unlocked_R (node=node@entry=0x7ffff4459b70, detail=detail@entry=0, instance=instance@entry=0x7ffff445d180, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffd1e0)
    at ../gobject/gsignal.c:3796
    #19 0x00007ffff6df3cbe in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd390) at ../gobject/gsignal.c:3549
#21 0x00007ffff7d5d4e4 in  () at /usr/lib/libxmpp-vala.so.0
#25 0x00007ffff6df3e9f in <emit signal ??? on instance 0x7fffde61b080 [XmppStartTlsXmppStream]> (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../gobject/gsignal.c:3606
    #22 0x00007ffff6dda430 in g_closure_invoke (closure=0x7fffec7501e0, return_value=return_value@entry=0x0, n_param_values=3, param_values=param_values@entry=0x7fffffffd650, invocation_hint=invocation_hint@entry=0x7fffffffd5d0) at ../gobject/gclosure.c:832
    #23 0x00007ffff6ded4c6 in signal_emit_unlocked_R (node=node@entry=0x7fffda2a0a20, detail=detail@entry=0, instance=instance@entry=0x7fffde61b080, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffd650)
    at ../gobject/gsignal.c:3796
    #24 0x00007ffff6df3cbe in g_signal_emit_valist (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffd800) at ../gobject/gsignal.c:3549
#26 0x00007ffff7d46d7c in  () at /usr/lib/libxmpp-vala.so.0
#27 0x00007ffff7d4717f in  () at /usr/lib/libxmpp-vala.so.0
#28 0x00007ffff6cdfbaf in g_main_dispatch (context=0x7ffff641be90) at ../glib/gmain.c:3454
#29 g_main_context_dispatch (context=0x7ffff641be90) at ../glib/gmain.c:4172
#30 0x00007ffff6cdff68 in g_main_context_iterate (context=context@entry=0x7ffff641be90, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4248
#31 0x00007ffff6cdfffc in g_main_context_iteration (context=context@entry=0x7ffff641be90, may_block=may_block@entry=1) at ../glib/gmain.c:4313
#32 0x00007ffff6effc1d in g_application_run (application=0x7ffff4c77f60 [DinoUiApplication], argc=<optimized out>, argv=<optimized out>) at ../gio/gapplication.c:2573
#33 0x0000555555582dc8 in main ()
```

**Comment by mar-v-in** [comment]
Can't reproduce this on fresh AlpineLinux 3.17 with Dino 0.4.1 from the repository
