### ISSUE TITLE
Dino hangs with 100% cpu

### ISSUE THREAD

**Issue by MarcelWaldvogel** [dino/dino#156]
I run Dino 0.0~git174.1f0df86-0 from OBS on Ubuntu 17.04 on a Laptop, which I unplug (monitor, network) regularly and put it to sleep.

It has happened twice now that after some time, Dino is no longer responding. I don't know how to reproduce this reliably, but here is some debugging information which might help. Please let me know which additional information I should collect on the next hang.

## gdb
```gdb
(gdb) attach 21874
Attaching to process 21874
[New LWP 21895]
[New LWP 21896]
[New LWP 22059]
[New LWP 22156]
[New LWP 9656]
[New LWP 10497]
[New LWP 14714]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f50f1d13d8d in poll () at ../sysdeps/unix/syscall-template.S:84
84	../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt
#0  0x00007f50f1d13d8d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f50f2028576 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f50f202868c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f50f25e34dd in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x0000556b2d5a92ca in dino_main ()
#5  0x0000556b2d5a8fe0 in main ()
(gdb) 
```

## strace -ff -p 21874
```strace
[pid 21874] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1831) = 1 ([{fd=3, revents=POLLIN}])
[pid 21874] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1831) = 1 ([{fd=3, revents=POLLIN}])
[pid 21874] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1831) = 1 ([{fd=3, revents=POLLIN}])
[pid 21874] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1831) = 1 ([{fd=3, revents=POLLIN}])
[pid 21874] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1831) = 1 ([{fd=3, revents=POLLIN}])
[pid 21874] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1831) = 1 ([{fd=3, revents=POLLIN}])
[pid 21874] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1831) = 1 ([{fd=3, revents=POLLIN}])
[pid 21874] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1831) = 1 ([{fd=3, revents=POLLIN}])
[pid 22156] <... nanosleep resumed> 0x7f50bfffeb00) = 0
[pid 22156] sched_yield()               = 0
[pid 22156] nanosleep({0, 100000000},  <unfinished ...>
[pid 21874] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1822) = 1 ([{fd=3, revents=POLLIN}])
[pid 21874] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1822) = 1 ([{fd=3, revents=POLLIN}])
[pid 21874] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1822) = 1 ([{fd=3, revents=POLLIN}])
[pid 21874] poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1821) = 1 ([{fd=3, revents=POLLIN}])

[…]

poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1) = 1 ([{fd=3, revents=POLLIN}])
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1) = 1 ([{fd=3, revents=POLLIN}])
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1) = 1 ([{fd=3, revents=POLLIN}])
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 1) = 1 ([{fd=3, revents=POLLIN}])
sendto(159, "\27\3\3\0\211\0\0\0\0\0\0\6\352\207\0\325\374/z\352$\223\200\357\3229 e\326\374\202A"..., 142, MSG_NOSIGNAL, NULL, 0) = 142
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 5000) = 1 ([{fd=3, revents=POLLIN}])
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 5000) = 1 ([{fd=3, revents=POLLIN}])
poll([{fd=3, events=POLLIN}, {fd=4, events=POLLIN}, {fd=5, events=POLLIN}], 3, 5000) = 1 ([{fd=3, revents=POLLIN}])
```

## lsof -p 21874
```lsof
dino    21874 marcel    0r      CHR                1,3      0t0         7 /dev/null
dino    21874 marcel    1u     unix 0xffff90ecba036800      0t0   2273607 type=STREAM
dino    21874 marcel    2u     unix 0xffff90ecba036800      0t0   2273607 type=STREAM
dino    21874 marcel    3u     unix 0xffff90ed49470800      0t0   2274644 type=STREAM
dino    21874 marcel    4u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel    5u     unix 0xffff90eedf7dd000      0t0   2272749 type=STREAM
dino    21874 marcel    6u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel    7u      REG               0,23   258048   3589180 /home/marcel/.local/share/dino/dino.db
dino    21874 marcel    8u     unix 0xffff90ef1ef8c000      0t0   2272750 type=STREAM
dino    21874 marcel    9u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel   10u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel   11u     unix 0xffff90ecd28fe000      0t0   2273631 type=STREAM
dino    21874 marcel   12u      REG               0,23   110592   3589198 /home/marcel/.local/share/dino/omemo.db
dino    21874 marcel   13u      REG               0,23    24576   3589211 /home/marcel/.local/share/dino/pgp.db
dino    21874 marcel   14u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel   15u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel   16u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel   17r  a_inode               0,11        0      9670 inotify
dino    21874 marcel   18u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel   19u     unix 0xffff90ec84472000      0t0   9111330 type=DGRAM
dino    21874 marcel   20u     unix 0xffff90ef2a215800      0t0   2272855 type=STREAM
dino    21874 marcel   21u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel   22u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel   23u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel   24u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel   25u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel   26u     IPv4            9494238      0t0       TCP myhost:36096->xmpp-server1:xmpp-client (ESTABLISHED)
dino    21874 marcel   27u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel   28u  a_inode               0,11        0      9670 [eventfd]

[…]

dino    21874 marcel  156u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel  157u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel  158u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel  159u     IPv4            9716386      0t0       TCP myhost:49864->xmpp-server2:xmpp-client (ESTABLISHED)
dino    21874 marcel  160u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel  161u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel  162u  a_inode               0,11        0      9670 [eventfd]

[…]

dino    21874 marcel  954u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel  955u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel  956u  a_inode               0,11        0      9670 [eventfd]
dino    21874 marcel  957u  a_inode               0,11        0      9670 [eventfd]
```

**Comment by NicoHood** [comment]
I've noticed that dino crashes for me sometimes. It just closes, but does not hang with 100% cpu. Might be a segmentation fault on arch. I only had this 2-3 times without any logs. Happens with  dino r168.d2a5287-1, upgrading now.

**Comment by zinid** [comment]
Same for me. It either crashes or falls into this infinity loop.

**Comment by fiaxh** [comment]
@MarcelWaldvogel Does the 100%-CPU problem still occur with the current HEAD? If so, please check if it hangs with a different stack trace now.
@NicoHood, @zinid Whenever Dino crashes, please report a stack trace if possible.

**Comment by MarcelWaldvogel** [comment]
Haven't seen 100% CPU load recently. Will update if I run into
crashes/hogs again.
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/dino/dino
> ","title":"dino/dino","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in GitHub","url":"https://gi
> thub.com/dino/dino"}},"updates":{"snippets":[{"icon":"PERSON","messag
> e":"@fiaxh in #156: @MarcelWaldvogel Does the 100%-CPU problem still
> occur with the current HEAD? If so, please check if it hangs with a
> different stack trace now.\r\n@NicoHood, @zinid Whenever Dino
> crashes, please report a stack trace if
> possible."}],"action":{"name":"View Issue","url":"https://github.com/
> dino/dino/issues/156#issuecomment-347334193"}}}

**Comment by chrisballinger** [comment]
@MarcelWaldvogel You might want to change that API key

**Comment by MarcelWaldvogel** [comment]
Thanks; there are bad mobile mail clients out there.

However, I guess this is not *my* API key, but a global GitHub key, which they include in every mail sent out. Your notification mails should include the same API key. Please let me know if yours isn't the same.

**Comment by silberzwiebel** [comment]
Not sure if this fits here, if not, I'll happily open a new issue.
Running dino on macOS crashes every now and then. Following https://github.com/dino/dino/issues/156#issuecomment-347334193 I can provide a stack trace (collected with lldb instead of gdb due to some weird apple stuff again):

```
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fffba73ed42 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fffba82c457 libsystem_pthread.dylib`pthread_kill + 90
    frame #2: 0x00007fffba6a4420 libsystem_c.dylib`abort + 129
    frame #3: 0x000000010068b527 libglib-2.0.0.dylib`g_assertion_message + 372
    frame #4: 0x000000010068b585 libglib-2.0.0.dylib`g_assertion_message_expr + 94
    frame #5: 0x0000000100ddadfb libgdk-3.0.dylib`select_thread_collect_poll + 348
    frame #6: 0x0000000100dda0bb libgdk-3.0.dylib`poll_func + 206
    frame #7: 0x000000010066c10c libglib-2.0.0.dylib`g_main_context_iterate + 340
    frame #8: 0x000000010066c1ba libglib-2.0.0.dylib`g_main_context_iteration + 55
    frame #9: 0x00000001003d8c56 libgio-2.0.0.dylib`g_application_run + 468
    frame #10: 0x00000001000057df dino`dino_main(args=0x00007fff5fbff900, args_length1=1) at main.vala:22
    frame #11: 0x0000000100005ab2 dino`main(argc=1, argv=0x00007fff5fbff900) at main.vala:9
    frame #12: 0x00007fffba610235 libdyld.dylib`start + 1
```

Btw, do you want to have all the failed assertion also to be reported? I got plenty ...

**Comment by zinid** [comment]
> @NicoHood, @zinid Whenever Dino crashes, please report a stack trace if possible

I've been running master for about a week already: no crashes, no cpu loops.
So I consider the issue is fixed, at least for me.

**Comment by fiaxh** [comment]
I assume that this bug is fixed. Please open a new issue or say something in this one if the problem occurs again.
