### ISSUE TITLE
SEGFAULT in http upload code

### ISSUE THREAD

**Issue by Mic92** [dino/dino#158]
Dino crashes on startup after connecting to my prosody server (0.10.r7198+.2fd20f372cb)

```console
$ ulimit -c unlimited
$ ./dino
$ coredumpctl gdb
gdb> bt
#0  memcpy (__len=0x4, __src=0x202e6020, __dest=0x7fba202e0270) at /nix/store/s96g9b8rl9ab13v1by7n661h0hzpbgsw-glibc-2.25-49-dev/include/bits/string3.h:53
#1  _int_dup (self=0x202e6020) at /home/joerg/git/dino/plugins/http-files/src/manager.vala:16
#2  0x00007fba4602544e in gee_hash_map_real_set () from /nix/store/j71wmn6cdz4fp74rkmvwybfyyzfpaalb-libgee-0.18.0/lib/libgee-0.8.so.2
#3  0x00007fba301b0785 in __lambda10_ (_data6_=0x144a4a0, _data6_=0x144a4a0, max_file_size=0x202e6020, stream=<optimized out>) at /home/joerg/git/dino/plugins/http-files/src/manager.vala:72
#4  ___lambda10__dino_plugins_http_files_upload_stream_module_feature_available (_sender=<optimized out>, stream=<optimized out>, max_file_size=0x202e6020, self=0x144a4a0) at /home/joerg/git/dino/plugins/http-files/src/manager.vala:70
#5  0x00007fba43a19a25 in g_closure_invoke () from /nix/store/n7a9cwc1346dx7iyjk5qv93d9ma31q7d-glib-2.52.3/lib/libgobject-2.0.so.0
#6  0x00007fba43a2b9a2 in signal_emit_unlocked_R () from /nix/store/n7a9cwc1346dx7iyjk5qv93d9ma31q7d-glib-2.52.3/lib/libgobject-2.0.so.0
#7  0x00007fba43a345fc in g_signal_emit_valist () from /nix/store/n7a9cwc1346dx7iyjk5qv93d9ma31q7d-glib-2.52.3/lib/libgobject-2.0.so.0
#8  0x00007fba43a34e8b in g_signal_emit_by_name () from /nix/store/n7a9cwc1346dx7iyjk5qv93d9ma31q7d-glib-2.52.3/lib/libgobject-2.0.so.0
#9  0x00007fba301b2a95 in dino_plugins_http_files_upload_stream_module_check_ns_in_info (self=0x1355560, stream=0x15a8410, jid=0x7fba2026b400 "jabber.higgsboson.tk", info_result=<optimized out>) at /home/joerg/git/dino/plugins/http-files/src/upload_stream_module.vala:132
#10 0x00007fba4650c8e2 in __lambda6_ (_data2_=0x7fba20262c70, _data2_=0x7fba20262c70, iq=<optimized out>, stream=0x15a8410) at /home/joerg/git/dino/xmpp-vala/src/module/xep/0030_service_discovery/module.vala:49
#11 ___lambda6__xmpp_iq_module_on_result (stream=0x15a8410, iq=<optimized out>, self=0x7fba20262c70) at /home/joerg/git/dino/xmpp-vala/src/module/xep/0030_service_discovery/module.vala:45
#12 0x00007fba464fb17e in xmpp_iq_module_on_received_iq_stanza (node=<optimized out>, stream=0x15a8410, self=0x165d9d0) at /home/joerg/git/dino/xmpp-vala/src/module/iq/module.vala:55
#13 _xmpp_iq_module_on_received_iq_stanza_xmpp_core_xmpp_stream_received_iq_stanza (_sender=<optimized out>, stream=0x15a8410, node=<optimized out>, self=0x165d9d0) at /home/joerg/git/dino/xmpp-vala/src/module/iq/module.vala:34
#14 0x00007fba43a19a25 in g_closure_invoke () from /nix/store/n7a9cwc1346dx7iyjk5qv93d9ma31q7d-glib-2.52.3/lib/libgobject-2.0.so.0
#15 0x00007fba43a2b9a2 in signal_emit_unlocked_R () from /nix/store/n7a9cwc1346dx7iyjk5qv93d9ma31q7d-glib-2.52.3/lib/libgobject-2.0.so.0
#16 0x00007fba43a345fc in g_signal_emit_valist () from /nix/store/n7a9cwc1346dx7iyjk5qv93d9ma31q7d-glib-2.52.3/lib/libgobject-2.0.so.0
#17 0x00007fba43a34e8b in g_signal_emit_by_name () from /nix/store/n7a9cwc1346dx7iyjk5qv93d9ma31q7d-glib-2.52.3/lib/libgobject-2.0.so.0
#18 0x00007fba464f8ced in xmpp_core_xmpp_stream_loop (error=0x7fba291bfbe8, self=0x15a8410) at /home/joerg/git/dino/xmpp-vala/src/core/xmpp_stream.vala:213
#19 xmpp_core_xmpp_stream_connect (self=self@entry=0x15a8410, remote_name=<optimized out>, error=error@entry=0x7fba291bfc80) at /home/joerg/git/dino/xmpp-vala/src/core/xmpp_stream.vala:70
#20 0x00007fba4698108e in __lambda10_ (_data2_=<optimized out>) at /home/joerg/git/dino/libdino/src/service/connection_manager.vala:173
#21 ___lambda10__gthread_func (self=0x1402a80) at connection_manager.c:1419
#22 0x00007fba437689e5 in g_thread_proxy () from /nix/store/n7a9cwc1346dx7iyjk5qv93d9ma31q7d-glib-2.52.3/lib/libglib-2.0.so.0
#23 0x00007fba42cca234 in start_thread () from /nix/store/bwax7l3946zn3l806727sd1fk8ssjgpv-glibc-2.25-49/lib/libpthread.so.0
#24 0x00007fba4344074f in clone () from /nix/store/bwax7l3946zn3l806727sd1fk8ssjgpv-glibc-2.25-49/lib/libc.so.6
```

Looking at the backtrace it looks like it is related to the http upload module - maybe even security releated?
If you need more information I can also do a git-bisect to find the first offending commit. The bug is 100% reproducible.

I also attached a valgrind report. Interestingly the crash does not happen their.
I used a suppression file for gtk from here https://wiki.gnome.org/Valgrind
[valgrind.txt](https://github.com/dino/dino/files/1317471/valgrind.txt) and also exported `G_DEBUG=gc-friendly G_SLICE=always-malloc`
Reported leaks might be false-positives though I am not too familiar with GObject.

**Comment by silberzwiebel** [comment]
same issue under korora 25 (based on fedora 25).
crashes with latest build from the opensuse repo, works with the latest build from the copr repo.
not sure if [this backtrace here helps, but it might](https://gist.github.com/silberzwiebel/9747cf9a9e73da685795ebe9d4d01503).

**Comment by silberzwiebel** [comment]
Oh, forgot to mention: the same version from the opensuse repo works just fine under Fedora _26_.

**Comment by Mic92** [comment]
Same jabber server?

**Comment by silberzwiebel** [comment]
not the same physical server, but an up-to-date prosody 0.10 nightly
(updated a few days ago).

**Comment by Mic92** [comment]
fixed by https://github.com/dino/dino/commit/9d8e1e88ec61403659a8cc410d5c4414e3bd3a96
