### ISSUE TITLE
Dino freezes after network connection change

### ISSUE THREAD

**Issue by RalfJung** [dino/dino#200]
I have not been able to trigger this reproducibly, but dino just entirely froze for the second time while using 100% of one CPU core. This time, I got a backtrace:
```
#0  0x00007f61d49ffb23 in __GI___pthread_mutex_lock (mutex=0x5577fe9ac060) at ../nptl/pthread_mutex_lock.c:67
#1  0x00007f61cf7f64a7 in dbus_connection_get_dispatch_status () at /lib/x86_64-linux-gnu/libdbus-1.so.3
#2  0x00007f61cfa49863 in  () at /usr/lib/x86_64-linux-gnu/libatspi.so.0
#3  0x00007f61d51fe658 in g_main_context_prepare () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f61d51ff04b in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f61d51ff22c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f61d57bcbed in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00005577fe42a38a in dino_main (args=0x7fff48dc9998, args_length1=1) at /home/r/src/dino/main/src/main.vala:22
#8  0x00005577fe42a4bf in main (argc=1, argv=0x7fff48dc9998) at /home/r/src/dino/main/src/main.vala:9
(gdb) thread apply all bt

Thread 7 (Thread 0x7f619fd7f700 (LWP 14657)):
#0  0x00007f61d4ef666d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f61d579862d in g_socket_condition_timed_wait () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#2  0x00007f61d57994ee in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#3  0x00007f61d577eb40 in g_input_stream_read () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f61af5ee435 in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
#5  0x00007f61aef7ed28 in  () at /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#6  0x00007f61aef78d5a in  () at /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#7  0x00007f61aef7a879 in  () at /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#8  0x00007f61af5eff03 in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
#9  0x00007f61af5f20e1 in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
#10 0x00007f61d577eb40 in g_input_stream_read () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#11 0x00007f61d81f628c in xmpp_core_stanza_reader_update_buffer (self=, error=0x7f619fd7e550) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:52
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#12 0x00007f61d81f677c in xmpp_core_stanza_reader_read_single (self=, error=0x7f619fd7e5b8) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:64
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#13 0x00007f61d81f68dc in xmpp_core_stanza_reader_peek_single (self=, error=0x7f619fd7e600) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:70
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#14 0x00007f61d81f6b28 in xmpp_core_stanza_reader_skip_until_non_ws (self=, error=0x7f619fd7e648) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:84
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#15 0x00007f61d81fc2a7 in xmpp_core_stanza_reader_read_node (self=, error=0x7f619fd7e6c8) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:258
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#16 0x00007f61d820323f in xmpp_core_xmpp_stream_read (self=, error=0x7f619fd7e778) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:103
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#17 0x00007f61d8204b8d in xmpp_core_xmpp_stream_loop (self=, error=0x7f619fd7e8c8) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:197
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#18 0x00007f61d8202937 in xmpp_core_xmpp_stream_connect (self=, remote_name=0x5577feac3420 "jabber.mpi-sws.org", error=0x7f619fd7ea90) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:70
#19 0x00007f61d86c3497 in __lambda10_ (_data2_=0x557801f90720) at /home/r/src/dino/libdino/src/service/connection_manager.vala:173
#20 0x00007f61d86c383e in ___lambda10__gthread_func (self=0x557801f90720) at connection_manager.c:1426
#21 0x00007f61d52265f5 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007f61d49fd494 in start_thread (arg=0x7f619fd7f700) at pthread_create.c:333
#23 0x00007f61d4effabf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 6 (Thread 0x7f61affff700 (LWP 11080)):
#0  0x00007f61d4ef666d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f61d579862d in g_socket_condition_timed_wait () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#2  0x00007f61d57994ee in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#3  0x00007f61d577eb40 in g_input_stream_read () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f61af5ee435 in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
#5  0x00007f61aef7ed28 in  () at /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#6  0x00007f61aef78d5a in  () at /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#7  0x00007f61aef7a879 in  () at /usr/lib/x86_64-linux-gnu/libgnutls.so.30
#8  0x00007f61af5eff03 in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
#9  0x00007f61af5f20e1 in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
#10 0x00007f61d577eb40 in g_input_stream_read () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#11 0x00007f61d81f628c in xmpp_core_stanza_reader_update_buffer (self=, error=0x7f61afffe550) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:52
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#12 0x00007f61d81f677c in xmpp_core_stanza_reader_read_single (self=, error=0x7f61afffe5b8) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:64
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#13 0x00007f61d81f68dc in xmpp_core_stanza_reader_peek_single (self=, error=0x7f61afffe600) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:70
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#14 0x00007f61d81f6b28 in xmpp_core_stanza_reader_skip_until_non_ws (self=, error=0x7f61afffe648) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:84
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#15 0x00007f61d81fc2a7 in xmpp_core_stanza_reader_read_node (self=, error=0x7f61afffe6c8) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:258
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#16 0x00007f61d820323f in xmpp_core_xmpp_stream_read (self=, error=0x7f61afffe778) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:103
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#17 0x00007f61d8204b8d in xmpp_core_xmpp_stream_loop (self=, error=0x7f61afffe8c8) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:197
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#18 0x00007f61d8202937 in xmpp_core_xmpp_stream_connect (self=, remote_name=0x5577feb0ee70 "jabber.ralfj.de", error=0x7f61afffea90) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:70
#19 0x00007f61d86c3497 in __lambda10_ (_data2_=0x557801d05400) at /home/r/src/dino/libdino/src/service/connection_manager.vala:173
#20 0x00007f61d86c383e in ___lambda10__gthread_func (self=0x557801d05400) at connection_manager.c:1426
#21 0x00007f61d52265f5 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007f61d49fd494 in start_thread (arg=0x7f61affff700) at pthread_create.c:333
#23 0x00007f61d4effabf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 5 (Thread 0x7f61ad18c700 (LWP 26285)):
#0  0x00007f61d4ecf27d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f61d5227ccf in g_usleep () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f61d7d20df2 in  () at /usr/lib/x86_64-linux-gnu/libgee-0.8.so.2
#3  0x00007f61d52265f5 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f61d49fd494 in start_thread (arg=0x7f61ad18c700) at pthread_create.c:333
#5  0x00007f61d4effabf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

---Type <return> to continue, or q <return> to quit---
Thread 4 (Thread 0x7f61bcc32700 (LWP 26280)):
#0  0x00007f61d4ef666d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f61d51ff119 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f61d51ff22c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f61bcc3a42d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007f61d52265f5 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f61d49fd494 in start_thread (arg=0x7f61bcc32700) at pthread_create.c:333
#6  0x00007f61d4effabf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 3 (Thread 0x7f61cca2c700 (LWP 26264)):
#0  0x00007f61d4ef666d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f61d51ff119 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f61d51ff4b2 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f61d57e8ad6 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f61d52265f5 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f61d49fd494 in start_thread (arg=0x7f61cca2c700) at pthread_create.c:333
#6  0x00007f61d4effabf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 2 (Thread 0x7f61cd22d700 (LWP 26263)):
#0  0x00007f61d4ef666d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007f61d51ff119 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f61d51ff22c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f61d51ff271 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f61d52265f5 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f61d49fd494 in start_thread (arg=0x7f61cd22d700) at pthread_create.c:333
#6  0x00007f61d4effabf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 1 (Thread 0x7f61d8ae8380 (LWP 26262)):
#0  0x00007f61d49ffb23 in __GI___pthread_mutex_lock (mutex=0x5577fe9ac060) at ../nptl/pthread_mutex_lock.c:67
#1  0x00007f61cf7f64a7 in dbus_connection_get_dispatch_status () at /lib/x86_64-linux-gnu/libdbus-1.so.3
#2  0x00007f61cfa49863 in  () at /usr/lib/x86_64-linux-gnu/libatspi.so.0
#3  0x00007f61d51fe658 in g_main_context_prepare () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f61d51ff04b in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f61d51ff22c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f61d57bcbed in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00005577fe42a38a in dino_main (args=0x7fff48dc9998, args_length1=1) at /home/r/src/dino/main/src/main.vala:22
#8  0x00005577fe42a4bf in main (argc=1, argv=0x7fff48dc9998) at /home/r/src/dino/main/src/main.vala:9
```

perf on this process shows the following:
```
  12,11%  libglib-2.0.so.0.5400.1           [.] g_mutex_lock
  12,09%  libglib-2.0.so.0.5400.1           [.] g_mutex_unlock
   6,80%  [kernel]                          [k] do_sys_poll
   6,24%  libglib-2.0.so.0.5400.1           [.] g_main_context_prepare
   5,82%  libglib-2.0.so.0.5400.1           [.] g_main_context_check
   3,78%  [kernel]                          [k] __fget
   2,54%  [kernel]                          [k] fput
   2,18%  [kernel]                          [k] unix_poll
   1,86%  [kernel]                          [k] _raw_spin_lock_irqsave
   1,77%  [kernel]                          [k] read_tsc
   1,64%  [kernel]                          [k] select_estimate_accuracy.part.9
   1,61%  libglib-2.0.so.0.5400.1           [.] 0x0000000000048049
   1,56%  [vdso]                            [.] 0x0000000000000977
   1,45%  [kernel]                          [.] system_call_fast_compare_end
   1,40%  [kernel]                          [k] ktime_get_ts64
   1,37%  [vdso]                            [.] __vdso_clock_gettime
   1,26%  [kernel]                          [k] _raw_spin_unlock_irqrestore
   1,14%  libglib-2.0.so.0.5400.1           [.] g_main_context_query
   1,06%  [unknown]                         [k] 0x00007f61d4ef666b
   0,99%  [kernel]                          [k] copy_user_generic_unrolled
   0,94%  libpthread-2.24.so                [.] __pthread_mutex_unlock_usercnt
   0,90%  [kernel]                          [k] entry_SYSCALL_64_after_swapgs
   0,84%  libpthread-2.24.so                [.] pthread_mutex_lock
   0,83%  [kernel]                          [k] __pollwait
   0,69%  libc-2.24.so                      [.] __libc_disable_asynccancel
   0,67%  libc-2.24.so                      [.] __libc_enable_asynccancel
   0,58%  libdbus-1.so.3.19.1 (deleted)     [.] 0x00000000000240f0
   0,57%  libglib-2.0.so.0.5400.1           [.] g_thread_self
   0,55%  libpthread-2.24.so                [.] pthread_getspecific
   0,51%  libglib-2.0.so.0.5400.1           [.] 0x0000000000048075
```

So, somehow it is going in a loop trying to acquire some lock, and does not do anything else.

**Comment by RalfJung** [comment]
Interestingly, even sending a SIGKILL does not kill the process. And there are two dino processes. Hu?

**Comment by RalfJung** [comment]
I just saw another freeze, this time with dino just being blocked an not taking any CPU:
```
#0  0x00007f19f56a6f5c in __lll_lock_wait () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
#1  0x00007f19f56a0c06 in __GI___pthread_mutex_lock (mutex=0x7f19d405a010) at ../nptl/pthread_mutex_lock.c:115
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#2  0x00007f19f8ea16e3 in xmpp_core_stanza_writer_write_node (self=, node=0x56509c3bbf70, error=0x7ffc2d89dae0) at /home/r/src/dino/xmpp-vala/src/core/stanza_writer.vala:11
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#3  0x00007f19f8ea7a7e in xmpp_core_xmpp_stream_write (self=, node=0x56509c3bbf70, error=0x7ffc2d89dba8) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:116
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#4  0x00007f19f8eaff5a in xmpp_iq_module_send_iq (self=0x56509bb0ec50, stream=, iq=0x7f19d40016d0, listener=0x7f19f8eebe5e <___lambda26__xmpp_iq_module_on_result>, listener_target=0x7f19cc01a530, listener_target_destroy_notify=0x7f19f8eebd1b <block18_data_unref>) at /home/r/src/dino/xmpp-vala/src/module/iq/module.vala:17
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#5  0x00007f19f8eec139 in xmpp_xep_ping_module_send_ping (self=0x56509b93d950, stream=, jid=0x56509b97a080 "jabber.mpi-sws.org", listener=0x7f19f936b7ef <___lambda5__xmpp_xep_ping_module_on_result>, listener_target=0x56509c36dd50, listener_target_destroy_notify=0x7f19f936b6c0 <block4_data_unref>) at /home/r/src/dino/xmpp-vala/src/module/xep/0199_ping.vala:15
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#6  0x00007f19f936beda in dino_connection_manager_check_reconnect (self=, account=0x56509b8c81d0) at /home/r/src/dino/libdino/src/service/connection_manager.vala:252
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#7  0x00007f19f936b66c in dino_connection_manager_check_reconnects (self=) at /home/r/src/dino/libdino/src/service/connection_manager.vala:243
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
Python Exception <class 'gdb.error'> There is no member named keys.: 
#8  0x00007f19f936889d in ___lambda12_ (self=, s=0x56509c10bc50 "org.freedesktop.NetworkManager", sv=0x56509befbcc0, sa=0x56509c107f70, sa_length1=0)
    at /home/r/src/dino/libdino/src/service/connection_manager.vala:82
Python Exception <class 'gdb.error'> There is no member named keys.: 
#9  0x00007f19f9368923 in ____lambda12__network_manager_dbus_properties_properties_changed (_sender=0x56509b83d580, iface=0x56509c10bc50 "org.freedesktop.NetworkManager", changed=0x56509befbcc0, invalidated=0x56509c107f70, invalidated_length1=0, self=0x56509b863a20) at /home/r/src/dino/libdino/src/service/connection_manager.vala:78
#10 0x00007f19f9342491 in g_cclosure_user_marshal_VOID__STRING_BOXED_BOXED_INT (closure=0x56509b8857b0, return_value=0x0, n_param_values=5, param_values=0x7ffc2d89e190, invocation_hint=0x7ffc2d89e110, marshal_data=0x0) at /home/r/src/dino/libdino/src/dbus/network_manager_dbus_properties.vala:2
#11 0x00007f19f6178f9d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007f19f618bcae in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007f19f6194485 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007f19f6195378 in g_signal_emit_by_name () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007f19f9342a35 in _dbus_handle_network_manager_dbus_properties_properties_changed (self=0x56509b83d580, parameters=0x7f19cc00e8f0) at network_manager_dbus_properties.c:185
#16 0x00007f19f9342ad1 in network_manager_dbus_properties_proxy_g_signal (proxy=0x56509b83d580, sender_name=0x56509b8bd220 ":1.12", signal_name=0x56509c382160 "PropertiesChanged", parameters=0x7f19cc00e8f0)
    at network_manager_dbus_properties.c:194
#17 0x00007f19f0d93038 in ffi_call_unix64 () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#18 0x00007f19f0d92a9a in ffi_call () at /usr/lib/x86_64-linux-gnu/libffi.so.6
#19 0x00007f19f6179799 in g_cclosure_marshal_generic () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#20 0x00007f19f6178f9d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#21 0x00007f19f618b728 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007f19f6194485 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007f19f6194e9f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007f19f6485fdc in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#25 0x00007f19f6475814 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#26 0x00007f19f5e9fdd5 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007f19f5ea01a0 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007f19f5ea022c in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007f19f645dbed in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#30 0x000056509a6283a2 in dino_main (args=0x7ffc2d89f2b8, args_length1=1) at /home/r/src/dino/main/src/main.vala:22
#31 0x000056509a6285af in main (argc=1, argv=0x7ffc2d89f2b8) at /home/r/src/dino/main/src/main.vala:9
```

**Comment by fiaxh** [comment]
This should not happen anymore.
