### ISSUE TITLE
Crash in xmpp_core_stanza_reader_update_buffer

### ISSUE THREAD

**Issue by RalfJung** [dino/dino#212]
Here's the backtrace:
```
#0  0x00007f6a041a1911 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007f6a041a294c in g_log_default_handler () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f6a041a2bdd in g_logv () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f6a041a2d4f in g_log () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f6a041e0181 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f6a046f5ba3 in g_cancellable_make_pollfd () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#6  0x00007f6a04735602 in g_socket_condition_timed_wait () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#7  0x00007f6a047364ee in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#8  0x00007f6a0471bb40 in g_input_stream_read () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#9  0x00007f6a07196780 in xmpp_core_stanza_reader_update_buffer (self=, error=0x7f69d2d7b470) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:52
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#10 0x00007f6a07196b3d in xmpp_core_stanza_reader_read_single (self=, error=0x7f69d2d7b4d8) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:62
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#11 0x00007f6a07196c9d in xmpp_core_stanza_reader_peek_single (self=, error=0x7f69d2d7b520) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:68
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#12 0x00007f6a07196ee9 in xmpp_core_stanza_reader_skip_until_non_ws (self=, error=0x7f69d2d7b568) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:82
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#13 0x00007f6a0719ac9a in xmpp_core_stanza_reader_read_root_node (self=, error=0x7f69d2d7b5f8) at /home/r/src/dino/xmpp-vala/src/core/stanza_reader.vala:208
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#14 0x00007f6a071a60be in xmpp_core_xmpp_stream_read_root (self=, error=0x7f69d2d7b6a8) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:273
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#15 0x00007f6a071a4c78 in xmpp_core_xmpp_stream_setup (self=, error=0x7f69d2d7b778) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:187
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#16 0x00007f6a071a4e76 in xmpp_core_xmpp_stream_loop (self=, error=0x7f69d2d7b8c8) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:193
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#17 0x00007f6a071a2cf8 in xmpp_core_xmpp_stream_connect (self=, remote_name=0x55664cc388c0 "$SERVER", error=0x7f69d2d7ba90) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:70
#18 0x00007f6a0766603e in __lambda10_ (_data2_=0x556650871a80) at /home/r/src/dino/libdino/src/service/connection_manager.vala:187
#19 0x00007f6a076663e5 in ___lambda10__gthread_func (self=0x556650871a80) at connection_manager.c:1662
#20 0x00007f6a041c35f5 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007f6a0399a494 in start_thread (arg=0x7f69d2d7c700) at pthread_create.c:333
#22 0x00007f6a03e9cabf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

I have a coredump, gut given how much sensitive data it contains, I'd rather not send that to anyone. I can use it to do further queries, though.

**Comment by RalfJung** [comment]
Actually, I think this coredump may be from our debugging session. gdb said "Program terminated with signal SIGTRAP, Trace/breakpoint trap.". So, never mind this.
