### ISSUE TITLE
Crash in dino_ui_conversation_selector_conversation_row_update_name_label

### ISSUE THREAD

**Issue by RalfJung** [dino/dino#213]
Here's the backtrace:
```
#0  0x00007f987fe2fa4b in  () at /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
#1  0x00007f987fe30f62 in pixman_region32_union () at /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
#2  0x00007f98844f8be0 in cairo_region_union () at /usr/lib/x86_64-linux-gnu/libcairo.so.2
#3  0x00007f988508891b in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#4  0x00007f98856addb2 in gtk_widget_queue_draw_area () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#5  0x00007f98856b530d in gtk_widget_queue_draw () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#6  0x00007f98856b56e8 in gtk_widget_queue_resize () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#7  0x00007f988554cece in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007f988554da43 in gtk_label_set_label () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#9  0x000055b32cc0ad31 in dino_ui_conversation_selector_conversation_row_update_name_label (self=0x55b32ed91c80, new_name=0x0) at /home/r/src/dino/main/src/ui/conversation_selector/conversation_row.vala:83
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#10 0x000055b32cc09779 in __lambda64_ (_data25_=0x55b32ea723a0, account=0x55b32e9939d0, jid=0x7f9848146720, roster_item=) at /home/r/src/dino/main/src/ui/conversation_selector/chat_row.vala:20
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#11 0x000055b32cc097bb in ___lambda64__dino_roster_manager_updated_roster_item (_sender=0x55b32e9e0560, account=0x55b32e9939d0, jid=0x7f9848146720, roster_item=, self=0x55b32ea723a0)
    at /home/r/src/dino/main/src/ui/conversation_selector/chat_row.vala:18
#12 0x00007f9886eb1745 in g_cclosure_user_marshal_VOID__OBJECT_OBJECT_XMPP_ROSTER_ITEM (closure=0x55b32ef05500, return_value=0x0, n_param_values=4, param_values=0x7f9855ef9410, invocation_hint=0x7f9855ef9390, marshal_data=0x0) at /home/r/src/dino/libdino/src/service/roster_manager.vala:8
#13 0x00007f9883c92f9d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007f9883ca5cae in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007f9883cae485 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007f9883caee9f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#17 0x00007f9886eb1601 in dino_roster_manager_on_roster_item_updated (self=0x55b32e9e0560, account=0x55b32e9939d0, roster_item=) at /home/r/src/dino/libdino/src/service/roster_manager.vala:72
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#18 0x00007f9886eb0f10 in __lambda38_ (_data17_=0x55b32ea50320, stream=, roster=0x7f9840013e10) at /home/r/src/dino/libdino/src/service/roster_manager.vala:60
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#19 0x00007f9886eb0f81 in ___lambda38__xmpp_roster_module_received_roster (_sender=0x55b32e9d84f0, stream=, roster=0x7f9840013e10, stanza=0x7f9848152c10, self=0x55b32ea50320)
    at /home/r/src/dino/libdino/src/service/roster_manager.vala:58
#20 0x00007f98869d43ee in g_cclosure_user_marshal_VOID__XMPP_CORE_XMPP_STREAM_OBJECT_OBJECT (closure=0x55b32ea5e360, return_value=0x0, n_param_values=4, param_values=0x7f9855ef9a60, invocation_hint=0x7f9855ef99e0, marshal_data=0x0) at /home/r/src/dino/xmpp-vala/src/module/roster/module.vala:9
#21 0x00007f9883c92f9d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#22 0x00007f9883ca5cae in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#23 0x00007f9883cae485 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007f9883caee9f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#25 0x00007f98869d4007 in xmpp_roster_module_on_roster_get_received (stream=, iq=0x7f9848152c10) at /home/r/src/dino/xmpp-vala/src/module/roster/module.vala:100
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#26 0x00007f98869d37bd in _xmpp_roster_module_on_roster_get_received_xmpp_iq_module_on_result (stream=, iq=0x7f9848152c10, self=0x0) at /home/r/src/dino/xmpp-vala/src/module/roster/module.vala:87
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#27 0x00007f98869cac09 in xmpp_iq_module_on_received_iq_stanza (self=0x55b32ec29b90, stream=, node=0x7f98400a1540) at /home/r/src/dino/xmpp-vala/src/module/iq/module.vala:60
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#28 0x00007f98869ca5e6 in _xmpp_iq_module_on_received_iq_stanza_xmpp_core_xmpp_stream_received_iq_stanza (_sender=, stream=, node=0x7f98400a1540, self=0x55b32ec29b90)
    at /home/r/src/dino/xmpp-vala/src/module/iq/module.vala:39
#29 0x00007f98869c473d in g_cclosure_user_marshal_VOID__XMPP_CORE_XMPP_STREAM_XMPP_CORE_STANZA_ENTRY (closure=0x7f9848001c40, return_value=0x0, n_param_values=3, param_values=0x7f9855efa490, invocation_hint=0x7f9855efa410, marshal_data=0x0) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:13
#30 0x00007f9883c92f9d in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007f9883ca5cae in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007f9883cae485 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#33 0x00007f9883caee9f in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#34 0x00007f98869c3487 in xmpp_core_xmpp_stream_loop (self=, error=0x7f9855efa8c8) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:213
Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
#35 0x00007f98869c0cf8 in xmpp_core_xmpp_stream_connect (self=, remote_name=0x55b32e92e7f0 "$SERVER", error=0x7f9855efaa90) at /home/r/src/dino/xmpp-vala/src/core/xmpp_stream.vala:70
#36 0x00007f9886e8403e in __lambda10_ (_data2_=0x55b32f5cfb20) at /home/r/src/dino/libdino/src/service/connection_manager.vala:187
#37 0x00007f9886e843e5 in ___lambda10__gthread_func (self=0x55b32f5cfb20) at connection_manager.c:1662
#38 0x00007f98839e15f5 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007f98831b8494 in start_thread (arg=0x7f9855efb700) at pthread_create.c:333
#40 0x00007f98836baabf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
```

I have a coredump that I can use to do some further queries, should that be helpful.

**Comment by fiaxh** [comment]
Should not happen anymore.
