### ISSUE TITLE
Dino sometimes crashes during MAM catchup

### ISSUE THREAD

**Issue by vanitasvitae** [dino/dino#407]
Sometimes Dino crashes when fetching messages after a start. If you need more debug information, let me know (how to get that :D).

```
**
ERROR:hashmap.c:3714:gee_hash_map_node_iterator_next: assertion failed: (_stamp == _map._stamp)
Abgebrochen (Speicherabzug geschrieben)
```

**Comment by vanitasvitae** [comment]
```
...
[Thread 0x7fffd603a700 (LWP 23838) exited]
**
ERROR:hashmap.c:3714:gee_hash_map_node_iterator_next: assertion failed: (_stamp == _map._stamp)

Thread 1 "dino" received signal SIGABRT, Aborted.
0x00007ffff53c586b in raise () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff53c586b in raise () at /usr/lib/libc.so.6
#1  0x00007ffff53b040e in abort () at /usr/lib/libc.so.6
#2  0x00007ffff57beb76 in g_assertion_message () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff57bebdc in g_assertion_message_expr ()
    at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff7428e9b in  () at /usr/lib/libgee-0.8.so.2
#5  0x00007ffff7badec5 in __lambda42_ (_data15_=0x555555a67d00, _data15_=0x555555a67d00, account=0x555555e9cf90)
    at /usr/src/debug/dino/libdino/src/service/notification_events.vala:33
#6  0x00007ffff7badec5 in ___lambda42__dino_message_processor_history_synced (_sender=<optimized out>, account=0x555555e9cf90, self=0x555555a67d00)
    at /usr/src/debug/dino/libdino/src/service/notification_events.vala:30
#7  0x00007ffff5a71a4d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff5a84e40 in  () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff5a8d6f6 in g_signal_emit_valist ()
    at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff5a8e130 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff792fabe in xmpp_xep_message_archive_management_module_page_through_results (stream=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, iq=<optimized out>, on_finished=<optimized out>, on_finished_target=<optimized out>, on_finished_target_destroy_notify=0x0)
    at /usr/src/debug/dino/xmpp-vala/src/module/xep/0313_message_archive_management.vala:61
#12 0x00007ffff79037d9 in xmpp_iq_module_on_received_iq_stanza (node=<optimized out>, stream=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, self=0x5555577c3150)
    at /usr/src/debug/dino/xmpp-vala/src/module/iq/module.vala:77
#13 0x00007ffff79037d9 in _xmpp_iq_module_on_received_iq_stanza_xmpp_xmpp_stream_received_iq_stanza (_sender=<optimized out>, stream=Python Exception <class 'ValueError'> Variable 'static_fundamental_type_nodes' not found.: 
, node=<optimized out>, self=0x5555577c3150) at /usr/src/debug/dino/xmpp-vala/src/module/iq/module.vala:33
#14 0x00007ffff5a71a4d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff5a84e40 in  () at /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff5a8d6f6 in g_signal_emit_valist ()
    at /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff5a8e130 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff79008c3 in xmpp_xmpp_stream_loop_co (_data_=0x555555c4e080)
    at /usr/src/debug/dino/xmpp-vala/src/core/xmpp_stream.vala:233
#19 0x00007ffff57971d6 in g_main_context_dispatch ()
    at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff57975b1 in  () at /usr/lib/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#21 0x00007ffff579763e in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff5d5897e in g_application_run () at /usr/lib/libgio-2.0.so.0
#23 0x000055555556f962 in dino_main (args=<optimized out>, args_length1=<optimized out>) at /usr/src/debug/dino/main/src/main.vala:22
#24 0x000055555556f6f0 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/dino/main/src/main.vala:9
```
