### ISSUE TITLE
dino crashes after launch with "free(): invalid pointer"

### ISSUE THREAD

**Issue by gimbar** [dino/dino#562]
I'm using dino via the AUR package dino-git[1] which fetches the current version from github and builds/installs it.
It started crashing without any action (regarding this package) from me.
I already tried building the latest version, but that results in the same bug.

[1] https://aur.archlinux.org/packages/dino-git/

**Comment by fiaxh** [comment]
Please provide a stack trace, which can be obtained as described [here](https://github.com/dino/dino/wiki/Debugging#stack-trace).

**Comment by gimbar** [comment]
```(gdb) start
Temporary breakpoint 1 at 0x1d0c0
Starting program: /usr/bin/dino 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

Temporary breakpoint 1, 0x00005555555710c0 in main ()
(gdb) continue
Continuing.
[New Thread 0x7ffff30e1700 (LWP 11986)]
[New Thread 0x7ffff28e0700 (LWP 11987)]
[New Thread 0x7ffff09af700 (LWP 11988)]
[New Thread 0x7fffe3fff700 (LWP 11989)]
[New Thread 0x7fffe32af700 (LWP 11991)]
[New Thread 0x7fffe2a20700 (LWP 11994)]
[New Thread 0x7fffe221f700 (LWP 11995)]
[New Thread 0x7fffe1a1e700 (LWP 11996)]
[New Thread 0x7fffe121d700 (LWP 11997)]
[New Thread 0x7fffcbfff700 (LWP 11998)]
[New Thread 0x7fffcb7fe700 (LWP 11999)]
[New Thread 0x7fffcaffd700 (LWP 12000)]
[New Thread 0x7fffca7fc700 (LWP 12001)]
[Thread 0x7fffca7fc700 (LWP 12001) exited]
[Thread 0x7fffcbfff700 (LWP 11998) exited]
[Thread 0x7fffe121d700 (LWP 11997) exited]
[Thread 0x7fffe1a1e700 (LWP 11996) exited]
[Thread 0x7fffe221f700 (LWP 11995) exited]
[Thread 0x7fffe2a20700 (LWP 11994) exited]
[Thread 0x7ffff09af700 (LWP 11988) exited]
[Thread 0x7fffe3fff700 (LWP 11989) exited]
[Thread 0x7fffcb7fe700 (LWP 11999) exited]
[New Thread 0x7fffcb7fe700 (LWP 12002)]
[New Thread 0x7fffe3fff700 (LWP 12003)]
[New Thread 0x7ffff09af700 (LWP 12004)]
free(): invalid pointer

Thread 1 "dino" received signal SIGABRT, Aborted.
0x00007ffff6b2e82f in raise () from /usr/lib/libc.so.6
```

**Comment by fiaxh** [comment]
The stack trace can be obtained by entering "bt" into gdb after Dino crashed. Please don't forget to [have debug symbols installed](https://wiki.archlinux.org/index.php/Debug_-_Getting_Traces_).

**Comment by gimbar** [comment]
```
(gdb) bt
#0  0x00007ffff6b2e82f in raise () at /usr/lib/libc.so.6
#1  0x00007ffff6b19672 in abort () at /usr/lib/libc.so.6
#2  0x00007ffff6b70e78 in __libc_message () at /usr/lib/libc.so.6
#3  0x00007ffff6b7778a in  () at /usr/lib/libc.so.6
#4  0x00007ffff6b78eb4 in _int_free () at /usr/lib/libc.so.6
#5  0x00007ffff19121c4 in signal_vala_decrypt
    (output=0x7fffffffe1f8, cipher=<optimized out>, key=<optimized out>, key_len=<optimized out>, iv=0x7fffffffe240 "\374\262\371\336om\022\350굘\302\a\003\064\237y", iv_len=<optimized out>, ciphertext=0x555556c155d8 "w\253$\324ְ֮8\306=~\367\030\227t]\322\367\367WD\v\003\354Y\371C\276I\264\304Q", ciphertext_len=<optimized out>, user_data=0x0)
    at ../plugins/signal-protocol/src/signal_helper.c:319
#6  0x00007ffff19203e9 in session_cipher_get_plaintext
    (cipher=0x555556c382d0, ciphertext_len=32, ciphertext=<optimized out>, message_keys=0x7fffffffe200, version=3, plaintext=<synthetic pointer>)
    at ../plugins/signal-protocol/libsignal-protocol-c/src/session_cipher.c:840
#7  0x00007ffff19203e9 in session_cipher_decrypt_from_state_and_signal_message
    (cipher=cipher@entry=0x555556c382d0, state=0x555556c60870, ciphertext=ciphertext@entry=0x555556c0e390, plaintext=plaintext@entry=0x7fffffffe338)
    at ../plugins/signal-protocol/libsignal-protocol-c/src/session_cipher.c:537
#8  0x00007ffff1920680 in session_cipher_decrypt_from_record_and_signal_message
    (cipher=cipher@entry=0x555556c382d0, record=0x555556c35510, ciphertext=0x555556c0e390, plaintext=plaintext@entry=0x7fffffffe398)
--Type <RET> for more, q to quit, c to continue without paging--
   ol/libsignal-protocol-c/src/session_cipher.c:403
#9  0x00007ffff1920f9a in session_cipher_decrypt_pre_key_signal_message (cipher=0x555556c382d0, ciphertext=0x555556c76f90, decrypt_context=decrypt_context@entry=0x0, plaintext=plaintext@entry=0x7fffffffe3f8)
    at ../plugins/signal-protocol/libsignal-protocol-c/src/session_cipher.c:288
#10 0x00007ffff19045e2 in session_cipher_decrypt_pre_key_signal_message_ (decrypt_context=0x0, error=0x555556c7d350, result_length1=0x555556c7d080, ciphertext=<optimized out>, self=<optimized out>)
    at /usr/src/debug/dino/build/exports/signal-protocol.vapi:294
#11 0x00007ffff19045e2 in dino_plugins_omemo_trust_manager_decrypt_message_listener_real_run_co (_data_=0x555556c7cb40) at /usr/src/debug/dino/plugins/omemo/src/trust_manager.vala:296
#12 0x00007ffff19045e2 in dino_plugins_omemo_trust_manager_decrypt_message_listener_real_run
    (base=<optimized out>, message=<optimized out>, stanza=<optimized out>, conversation=<optimized out>, _callback_=<optimized out>, _user_data_=<optimized out>)
    at /usr/src/debug/dino/plugins/omemo/src/trust_manager.vala:234
#13 0x00007ffff7f41d3b in dino_message_listener_holder_run_co (_data_=0x555556c54110) at /usr/src/debug/dino/libdino/src/service/message_processor.vala:292
#14 0x00007ffff7f317e5 in dino_counterpart_interaction_manager_received_message_listener_real_run_async_ready_wrapper (source_object=0x555555889b30, res=0x555555e769a0, user_data=0x555556c54110)
    at /usr/src/debug/dino/libdino/src/service/counterpart_interaction_manager.vala:134
#15 0x00007ffff70e20dc in  () at /usr/lib/libgio-2.0.so.0
#16 0x00007ffff70e2119 in  () at /usr/lib/libgio-2.0.so.0
#17 0x00007ffff6f017b1 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#18 0x00007ffff6f03869 in  () at /usr/lib/libglib-2.0.so.0
#19 0x00007ffff6f038ae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff70ba20e in g_application_run () at /usr/lib/libgio-2.0.so.0
#21 0x0000555555571352 in dino_main (args=<optimized out>, args_length1=<optimized out>) at /usr/src/debug/dino/main/src/main.vala:22
#22 0x00005555555710d0 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/dino/main/src/main.vala:9
```
