### ISSUE TITLE
Crash when receiving a file

### ISSUE THREAD

**Issue by Rahix** [dino/dino#619]
When receiving a file, either by syncing MAM or directly, Dino crashes for me.  Files were sent via HTTP-Upload.  Stack trace:
```
(gdb) bt
#0  0x00007f70b46f41e1 in dino_plugins_omemo_omemo_file_decryptor_real_decrypt_file_co (_data_=0x564ff1eb0ee0) at /home/rahix/Documents/Development/Dino/plugins/omemo/src/file_transfer/file_decryptor.vala:69
#1  0x00007f70b46f31e7 in dino_plugins_omemo_omemo_file_decryptor_decrypt_file_ready (source_object=0x564ff232ea70, _res_=0x564ff27c61b0, _user_data_=0x564ff1eb0ee0)
    at /home/rahix/Documents/Development/Dino/plugins/omemo/src/file_transfer/file_decryptor.vala:64
#2  0x00007f70b98dfb2c in  () at /usr/lib/libgio-2.0.so.0
#3  0x00007f70b98a6bf4 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007f70b98a6c29 in  () at /usr/lib/libgio-2.0.so.0
#5  0x00007f70b96d427f in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#6  0x00007f70b96d61c1 in  () at /usr/lib/libglib-2.0.so.0
#7  0x00007f70b96d6201 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#8  0x00007f70b98899ae in g_application_run () at /usr/lib/libgio-2.0.so.0
#9  0x0000564ff0a27306 in dino_main (args=0x7ffcc45dd7b8, args_length1=1) at /home/rahix/Documents/Development/Dino/main/src/main.vala:22
#10 0x0000564ff0a2750f in main (argc=1, argv=0x7ffcc45dd7b8) at /home/rahix/Documents/Development/Dino/main/src/main.vala:9
```

Looks like the `data.data` is a NULL-pointer:
```
(gdb) p _data_.data
$5 = (GArray *) 0x0
```

My (uninformed) guess is that for some reason nothing was read using `encrypted_stream.read_async(buf)` and thus the array is still empty.

**Comment by licaon-kter** [comment]
Dino version?

**Comment by Rahix** [comment]
If there is any further information I can provide or tests I should run, I'd be happy to do so!

**Comment by fiaxh** [comment]
This is fixed on master now.
