### ISSUE TITLE
Segmentation fault armhf

### ISSUE THREAD

**Issue by licaon-kter** [dino/dino#761]
Debian Buster, RPi 1 256Mb, armhf, HEAD (17acdd9f414a9e4d6a0607e94b03792581ff03df) build with `./configure --with-libsignal-in-tree`
```
pi@raspberrypi:~ $ gdb --args dino --g-fatal-warnings
GNU gdb (Raspbian 8.2.1-2) 8.2.1

Reading symbols from dino...done.
(gdb) r
Starting program: /usr/local/bin/dino --g-fatal-warnings
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0xb2f5d200 (LWP 1630)]
[New Thread 0xb25ff200 (LWP 1632)]
[New Thread 0xb0ce5200 (LWP 1667)]
[New Thread 0xafcec200 (LWP 1668)]
[New Thread 0xaf4eb200 (LWP 1669)]
[Thread 0xaf4eb200 (LWP 1669) exited]
[New Thread 0xaf4eb200 (LWP 1670)]
[Thread 0xaf4eb200 (LWP 1670) exited]
[New Thread 0xaeaea200 (LWP 1671)]
[New Thread 0xae1e0200 (LWP 1672)]
[New Thread 0xad8f0200 (LWP 1673)]
[Thread 0xae1e0200 (LWP 1672) exited]
[Thread 0xaeaea200 (LWP 1671) exited]
[New Thread 0xac87e200 (LWP 1674)]
[Thread 0xad8f0200 (LWP 1673) exited]
[Thread 0xac87e200 (LWP 1674) exited]
[New Thread 0xac07d200 (LWP 1675)]
[New Thread 0xab419200 (LWP 1676)]
[Thread 0xac07d200 (LWP 1675) exited]
[New Thread 0xaa4dd200 (LWP 1677)]
[Thread 0xab419200 (LWP 1676) exited]
[Thread 0xaa4dd200 (LWP 1677) exited]
[New Thread 0xa9cdc200 (LWP 1679)]
[Thread 0xafcec200 (LWP 1668) exited]

Thread 1 "dino" received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in  ()
#1  0xb6657a38 in  () at /usr/lib/arm-linux-gnueabihf/libgtk-3.so.0
```

I think OMEMO is at fault because if I delete the profile data, resetup and open a random unencrypted MUC it works fine.

**Comment by mar-v-in** [comment]
Have you tried using the libsignal-protocol-c2.3.2 from buster-backports and configure dino without `--with-libsignal-in-tree`?

**Comment by licaon-kter** [comment]
I can't use buster-backports for some reason (`Error:4 http://raspbian.raspberrypi.org/raspbian buster-backports Release  404  Not Found [IP: 93.93.128.193 80]`), but I see it in testing.

It will take a while to recompile though. :)

**Comment by licaon-kter** [comment]
Same error

```
pi@raspberrypi:~ $ env G_MESSAGES_DEBUG=libdino,OMEMO dino --print-xmpp=all
(dino:4765): libdino-DEBUG: 14:58:11.058: connection_manager.vala:159: [user@domain.tld] New connection with resource dino.13e00c2c: 0xb87ae8
(dino:4765): libdino-DEBUG: 14:58:11.168: message_processor.vala:53: MAM: [user@domain.tld] Reset catchup_id
XMPP OUT ROOT [user@domain.tld 0xb87ae8 2020-02-26T14:58:12+0200]
<stream to='convorb.im' version='1.0' xmlns='jabber:client' stream='http://etherx.jabber.org/streams'>

XMPP OUT [user@domain.tld 0xb87ae8 2020-02-26T14:58:12+0200]
<stream to='convorb.im' version='1.0' xmlns='jabber:client' stream='http://etherx.jabber.org/streams'>

XMPP IN ROOT [user@domain.tld 0xb87ae8 2020-02-26T14:58:12+0200]
<stream id='17618256511869393761' version='1.0' lang='en' stream='http://etherx.jabber.org/streams' from='convorb.im' xmlns='jabber:client'>

XMPP IN [user@domain.tld 0xb87ae8 2020-02-26T14:58:12+0200]
<features>
  <starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'>
    <required />
  </starttls>
</features>

Segmentation fault
```

**Comment by mar-v-in** [comment]
That doesn't look OMEMO related given that you are not receiving any omemo encrypted message...

**Comment by licaon-kter** [comment]
OK, renamed.

What next?

**Comment by mar-v-in** [comment]
Does the issue only happen when building from source or also with the package from debian repository?

**Comment by licaon-kter** [comment]
Raspbian (at least on RPi1) can't use Debian apps, different arch.

There is 0.1.0 in Testing but forces me to update libc and stuff, which I'd rather not do (for now).

**Comment by mar-v-in** [comment]
I tested Debian armhf release build in qemu user mode emulation and it works perfectly fine, so no idea what's going on here.

**Comment by licaon-kter** [comment]
Can I install some -dbg packages to further get some useful info?

**Comment by licaon-kter** [comment]
Never saw it after so...
